// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Update.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";
import type { StringBuilder } from "@tsonic/dotnet/System.Text.js";
import * as Microsoft_EntityFrameworkCore_Update_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Update.js";
import type { IModificationCommand, IModificationCommandBatchFactory, IModificationCommandFactory, INonTrackedModificationCommand, IReadOnlyModificationCommand, IUpdateSqlGenerator, ModificationCommand, ModificationCommandBatch, ModificationCommandBatchFactoryDependencies, ModificationCommandParameters, NonTrackedModificationCommandParameters, ResultSetMapping, UpdateAndSelectSqlGenerator, UpdateSqlGeneratorDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Update.js";

export interface SqliteLegacyUpdateSqlGenerator$instance {
}


export const SqliteLegacyUpdateSqlGenerator: {
    new(): SqliteLegacyUpdateSqlGenerator;
};


export type SqliteLegacyUpdateSqlGenerator = SqliteLegacyUpdateSqlGenerator$instance;

export interface SqliteModificationCommand$instance extends ModificationCommand {
}


export const SqliteModificationCommand: {
    new(modificationCommandParameters: ModificationCommandParameters): SqliteModificationCommand;
    new(modificationCommandParameters: NonTrackedModificationCommandParameters): SqliteModificationCommand;
};


export type SqliteModificationCommand = SqliteModificationCommand$instance;

export interface SqliteModificationCommandBatchFactory$instance {
    create(): ModificationCommandBatch;
}


export const SqliteModificationCommandBatchFactory: {
    new(dependencies: ModificationCommandBatchFactoryDependencies): SqliteModificationCommandBatchFactory;
};


export type SqliteModificationCommandBatchFactory = SqliteModificationCommandBatchFactory$instance;

export interface SqliteModificationCommandFactory$instance {
    createModificationCommand(modificationCommandParameters: ModificationCommandParameters): IModificationCommand;
    createNonTrackedModificationCommand(modificationCommandParameters: NonTrackedModificationCommandParameters): INonTrackedModificationCommand;
}


export const SqliteModificationCommandFactory: {
    new(): SqliteModificationCommandFactory;
};


export type SqliteModificationCommandFactory = SqliteModificationCommandFactory$instance;

export interface SqliteUpdateSqlGenerator$instance extends UpdateAndSelectSqlGenerator {
    appendDeleteOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
    appendInsertOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
    appendUpdateOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
    generateNextSequenceValueOperation(name: string, schema: string): string;
}


export const SqliteUpdateSqlGenerator: {
    new(dependencies: UpdateSqlGeneratorDependencies): SqliteUpdateSqlGenerator;
};


export type SqliteUpdateSqlGenerator = SqliteUpdateSqlGenerator$instance;

