// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Update.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { StringBuilder } from "@tsonic/dotnet/System.Text.js";
import type { ISqlGenerationHelper } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";
import * as Microsoft_EntityFrameworkCore_Update_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Update.js";
import type { ColumnModificationParameters, IColumnModification, IModificationCommand, IModificationCommandBatchFactory, IModificationCommandFactory, INonTrackedModificationCommand, IReadOnlyModificationCommand, IUpdateSqlGenerator, ModificationCommand, ModificationCommandBatch, ModificationCommandBatchFactoryDependencies, ModificationCommandParameters, NonTrackedModificationCommandParameters, ResultSetMapping, UpdateAndSelectSqlGenerator, UpdateSqlGeneratorDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Update.js";

export interface SqliteLegacyUpdateSqlGenerator$instance {
}


export const SqliteLegacyUpdateSqlGenerator: {
    new(): SqliteLegacyUpdateSqlGenerator;
};


export type SqliteLegacyUpdateSqlGenerator = SqliteLegacyUpdateSqlGenerator$instance;

export interface SqliteModificationCommand$instance extends ModificationCommand {
    ProcessSinglePropertyJsonUpdate(parameters: ColumnModificationParameters): void;
}


export const SqliteModificationCommand: {
    new(modificationCommandParameters: ModificationCommandParameters): SqliteModificationCommand;
    new(modificationCommandParameters: NonTrackedModificationCommandParameters): SqliteModificationCommand;
};


export type SqliteModificationCommand = SqliteModificationCommand$instance;

export interface SqliteModificationCommandBatchFactory$instance {
    readonly Dependencies: ModificationCommandBatchFactoryDependencies;
    Create(): ModificationCommandBatch;
}


export const SqliteModificationCommandBatchFactory: {
    new(dependencies: ModificationCommandBatchFactoryDependencies): SqliteModificationCommandBatchFactory;
};


export type SqliteModificationCommandBatchFactory = SqliteModificationCommandBatchFactory$instance;

export interface SqliteModificationCommandFactory$instance {
    CreateModificationCommand(modificationCommandParameters: ModificationCommandParameters): IModificationCommand;
    CreateNonTrackedModificationCommand(modificationCommandParameters: NonTrackedModificationCommandParameters): INonTrackedModificationCommand;
}


export const SqliteModificationCommandFactory: {
    new(): SqliteModificationCommandFactory;
};


export type SqliteModificationCommandFactory = SqliteModificationCommandFactory$instance;

export interface SqliteUpdateSqlGenerator$instance extends UpdateAndSelectSqlGenerator {
    AppendDeleteOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
    AppendIdentityWhereCondition(commandStringBuilder: StringBuilder, columnModification: IColumnModification): void;
    AppendInsertOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
    AppendRowsAffectedWhereCondition(commandStringBuilder: StringBuilder, expectedRowsAffected: int): void;
    AppendSelectAffectedCountCommand(commandStringBuilder: StringBuilder, name: string, schema: string, commandPosition: int): ResultSetMapping;
    AppendUpdateColumnValue(updateSqlGeneratorHelper: ISqlGenerationHelper, columnModification: IColumnModification, stringBuilder: StringBuilder, name: string, schema: string): void;
    AppendUpdateOperation(commandStringBuilder: StringBuilder, command: IReadOnlyModificationCommand, commandPosition: int, requiresTransaction: boolean): ResultSetMapping;
    GenerateNextSequenceValueOperation(name: string, schema: string): string;
}


export const SqliteUpdateSqlGenerator: {
    new(dependencies: UpdateSqlGeneratorDependencies): SqliteUpdateSqlGenerator;
};


export type SqliteUpdateSqlGenerator = SqliteUpdateSqlGenerator$instance;

