// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Scaffolding.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.Sqlite.Scaffolding.Internal/internal/index.js';

// Core type aliases from @tsonic/core
import type { fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Cross-namespace type imports for constraints
import type { DbConnection } from '@tsonic/dotnet/System.Data.Common.js';
import type { String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { MethodCallCodeFragment } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Design.js';
import type { IDiagnosticsLogger } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js';
import type { DbLoggerCategory_Scaffolding } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.js';
import type { DatabaseModelFactory, DatabaseModelFactoryOptions, IDatabaseModelFactory, IProviderConfigurationCodeGenerator, ProviderCodeGenerator, ProviderCodeGeneratorDependencies } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Scaffolding.js';
import type { DatabaseModel, DatabaseTable } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Scaffolding.Metadata.js';
import type { IRelationalTypeMappingSource } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqliteCodeGenerator as SqliteCodeGenerator } from './Microsoft.EntityFrameworkCore.Sqlite.Scaffolding.Internal/internal/index.js';
export { SqliteDatabaseModelFactory as SqliteDatabaseModelFactory } from './Microsoft.EntityFrameworkCore.Sqlite.Scaffolding.Internal/internal/index.js';
