// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Infrastructure
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js';

// Cross-namespace type imports for constraints
import type { SqliteOptionsExtension } from './Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal/internal/index.js';
import type { DbConnection } from '@tsonic/dotnet/System.Data.Common.js';
import type { Boolean as ClrBoolean, Object as ClrObject, Void } from '@tsonic/dotnet/System.js';
import type { IRelationalDbContextOptionsBuilderInfrastructure, RelationalDbContextOptionsBuilder } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js';
import type { DbContextOptionsBuilder } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SpatialiteLoader$instance as SpatialiteLoader } from './Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js';
export { SqliteDbContextOptionsBuilder as SqliteDbContextOptionsBuilder } from './Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js';
