// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal/internal/index.js';

// Cross-namespace type imports for constraints
import type { Func, String as ClrString, Type } from '@tsonic/dotnet/System.js';
import type { EventData, EventDefinitionBase, RelationalLoggingDefinitions } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqliteLoggingDefinitions as SqliteLoggingDefinitions } from './Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal/internal/index.js';
export { TableRebuildEventData as TableRebuildEventData } from './Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal/internal/index.js';
export { UnexpectedConnectionTypeEventData as UnexpectedConnectionTypeEventData } from './Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal/internal/index.js';
