// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.DependencyModel
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.Extensions.DependencyModel/internal/index.js';

// Cross-namespace type imports for constraints
import type { ICompilationAssemblyResolver } from './Microsoft.Extensions.DependencyModel.Resolution/internal/index.js';
import type { IEnumerable, IReadOnlyList } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Stream } from '@tsonic/dotnet/System.IO.js';
import type { Boolean as ClrBoolean, IDisposable, IEquatable, Int32, Nullable, Object as ClrObject, String as ClrString, ValueType, Void } from '@tsonic/dotnet/System.js';
import type { Assembly, AssemblyName } from '@tsonic/dotnet/System.Reflection.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CompilationLibrary as CompilationLibrary } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { CompilationOptions as CompilationOptions } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { Dependency as Dependency } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { DependencyContext as DependencyContext } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { DependencyContextExtensions$instance as DependencyContextExtensions } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { DependencyContextJsonReader as DependencyContextJsonReader } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { DependencyContextLoader as DependencyContextLoader } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { DependencyContextWriter as DependencyContextWriter } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export type IDependencyContextReader = Internal.IDependencyContextReader;
export { Library as Library } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { ResourceAssembly as ResourceAssembly } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { RuntimeAssembly as RuntimeAssembly } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { RuntimeAssetGroup as RuntimeAssetGroup } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { RuntimeFallbacks as RuntimeFallbacks } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { RuntimeFile as RuntimeFile } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { RuntimeLibrary as RuntimeLibrary } from './Microsoft.Extensions.DependencyModel/internal/index.js';
export { TargetInfo as TargetInfo } from './Microsoft.Extensions.DependencyModel/internal/index.js';
// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_Extensions_DependencyModel as ExtensionMethods } from './__internal/extensions/index.js';

