// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.Sqlite.Internal/internal/index.js';

// Cross-namespace type imports for constraints
import type { SqliteValueGenerationStrategy } from './Microsoft.EntityFrameworkCore.Metadata/internal/index.js';
import type { Boolean as ClrBoolean, Int64, Nullable, Object as ClrObject, String as ClrString, Type, Void } from '@tsonic/dotnet/System.js';
import type { EventDefinition, IDiagnosticsLogger } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js';
import type { DbLoggerCategory$Infrastructure, DbLoggerCategory$Migrations, DbLoggerCategory$Model$Validation, DbLoggerCategory$Scaffolding } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.js';
import type { IEntityType, IKey, IReadOnlyProperty, IReadOnlySequence } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqliteLoggerExtensions$instance as SqliteLoggerExtensions } from './Microsoft.EntityFrameworkCore.Sqlite.Internal/internal/index.js';
export { SqliteStrings$instance as SqliteStrings } from './Microsoft.EntityFrameworkCore.Sqlite.Internal/internal/index.js';
export { SqliteResources$instance as SqliteResources } from './Microsoft.EntityFrameworkCore.Sqlite.Internal/internal/index.js';
// Extension methods (C# using semantics)
export type { ExtensionMethods_Microsoft_EntityFrameworkCore_Sqlite_Internal as ExtensionMethods } from './__internal/extensions/index.js';

