// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Migrations.Internal
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore.Sqlite.Migrations.Internal/internal/index.js';

// Cross-namespace type imports for constraints
import type { Boolean as ClrBoolean, IAsyncDisposable, IDisposable, Object as ClrObject, String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { CancellationToken } from '@tsonic/dotnet/System.Threading.js';
import type { Task, ValueTask } from '@tsonic/dotnet/System.Threading.Tasks.js';
import type { HistoryRepository, HistoryRepositoryDependencies, IHistoryRepository, IMigrationsDatabaseLock, LockReleaseBehavior } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.js';
import type { IRelationalCommand, RelationalCommandParameterObject } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqliteHistoryRepository as SqliteHistoryRepository } from './Microsoft.EntityFrameworkCore.Sqlite.Migrations.Internal/internal/index.js';
export { SqliteMigrationDatabaseLock as SqliteMigrationDatabaseLock } from './Microsoft.EntityFrameworkCore.Sqlite.Migrations.Internal/internal/index.js';
