// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './Microsoft.EntityFrameworkCore/internal/index.js';

// Cross-namespace type imports for constraints
import type { SqliteDbContextOptionsBuilder } from './Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js';
import type { SqliteValueGenerationStrategy } from './Microsoft.EntityFrameworkCore.Metadata/internal/index.js';
import type { DbConnection } from '@tsonic/dotnet/System.Data.Common.js';
import type { Action, Boolean as ClrBoolean, Byte, Int32, Nullable, Object as ClrObject, String as ClrString, Void } from '@tsonic/dotnet/System.js';
import type { DatabaseFacade } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js';
import type { DbContext, DbContextOptionsBuilder, DbFunctions } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.js';
import type { ColumnBuilder, ComplexTypePropertyBuilder, IConventionEntityTypeBuilder, IConventionPropertyBuilder, OwnedNavigationTableBuilder, PropertyBuilder, SplitTableBuilder, TableBuilder } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Builders.js';
import type { ConfigurationSource, IConventionEntityType, IConventionEntityTypeMappingFragment, IConventionProperty, IConventionRelationalPropertyOverrides, IMutableEntityType, IMutableEntityTypeMappingFragment, IMutableProperty, IMutableRelationalPropertyOverrides, IReadOnlyEntityType, IReadOnlyEntityTypeMappingFragment, IReadOnlyProperty, IReadOnlyRelationalPropertyOverrides, ITable, StoreObjectIdentifier } from '@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { SqliteComplexTypePropertyBuilderExtensions$instance as SqliteComplexTypePropertyBuilderExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqliteDatabaseFacadeExtensions$instance as SqliteDatabaseFacadeExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqliteDbContextOptionsBuilderExtensions$instance as SqliteDbContextOptionsBuilderExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqliteDbFunctionsExtensions$instance as SqliteDbFunctionsExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqliteEntityTypeBuilderExtensions$instance as SqliteEntityTypeBuilderExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqliteEntityTypeExtensions$instance as SqliteEntityTypeExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqliteEntityTypeMappingFragmentExtensions$instance as SqliteEntityTypeMappingFragmentExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqlitePropertyBuilderExtensions$instance as SqlitePropertyBuilderExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqlitePropertyExtensions$instance as SqlitePropertyExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqliteTableBuilderExtensions$instance as SqliteTableBuilderExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
export { SqliteTableExtensions$instance as SqliteTableExtensions } from './Microsoft.EntityFrameworkCore/internal/index.js';
