// Generated by tsbindgen - Architecture
// Namespace: System.Collections.Generic
// Facade - Public API Surface

// Import internal declarations
import * as Internal from './System.Collections.Generic/internal/index.js';

// Cross-namespace type imports for constraints
import type { RuntimeAssetGroup, RuntimeFile } from './Microsoft.Extensions.DependencyModel/internal/index.js';
import type { IEnumerable } from '@tsonic/dotnet/System.Collections.Generic.js';
import type { Object as ClrObject, String as ClrString } from '@tsonic/dotnet/System.js';

// Public API exports (curated - no internal $instance/$views leakage)
export { CollectionExtensions$instance as CollectionExtensions } from './System.Collections.Generic/internal/index.js';
// Extension methods (C# using semantics)
export type { ExtensionMethods_System_Collections_Generic as ExtensionMethods } from './__internal/extensions/index.js';

