// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Diagnostics
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Abstractions, Microsoft.EntityFrameworkCore.Relational, Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { SqliteValueGenerationStrategy } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Func, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";
import * as Microsoft_EntityFrameworkCore_Diagnostics_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";
import type { EventData, EventDefinitionBase } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";
import type { IReadOnlyProperty } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import type { EventId } from "@tsonic/microsoft-extensions/Microsoft.Extensions.Logging.js";

export interface ConflictingValueGenerationStrategiesEventData$instance extends EventData {
    readonly otherValueGenerationStrategy: string;
    readonly property: IReadOnlyProperty;
    readonly sqliteValueGenerationStrategy: SqliteValueGenerationStrategy;
}


export const ConflictingValueGenerationStrategiesEventData: {
    new(eventDefinition: EventDefinitionBase, messageGenerator: Func<EventDefinitionBase, EventData, System_Internal.String>, sqliteValueGenerationStrategy: SqliteValueGenerationStrategy, otherValueGenerationStrategy: string, property: IReadOnlyProperty): ConflictingValueGenerationStrategiesEventData;
};


export type ConflictingValueGenerationStrategiesEventData = ConflictingValueGenerationStrategiesEventData$instance;

export abstract class SqliteEventId$instance {
    static readonly schemaConfiguredWarning: EventId;
    static readonly sequenceConfiguredWarning: EventId;
    static readonly compositeKeyWithValueGeneration: EventId;
    static readonly conflictingValueGenerationStrategiesWarning: EventId;
    static readonly unexpectedConnectionTypeWarning: EventId;
    static readonly tableRebuildPendingWarning: EventId;
    static readonly columnFound: EventId;
    static readonly schemasNotSupportedWarning: EventId;
    static readonly foreignKeyReferencesMissingTableWarning: EventId;
    static readonly tableFound: EventId;
    static readonly missingTableWarning: EventId;
    static readonly foreignKeyPrincipalColumnMissingWarning: EventId;
    static readonly indexFound: EventId;
    static readonly foreignKeyFound: EventId;
    static readonly primaryKeyFound: EventId;
    static readonly uniqueConstraintFound: EventId;
    static readonly inferringTypes: EventId;
    static readonly outOfRangeWarning: EventId;
    static readonly formatWarning: EventId;
}


export type SqliteEventId = SqliteEventId$instance;

