// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Abstractions, Microsoft.EntityFrameworkCore.Relational, Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { SqliteDbContextOptionsBuilder } from "../../Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { SqliteValueGenerationStrategy } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { DbConnection } from "@tsonic/dotnet/System.Data.Common.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Action, Boolean as ClrBoolean, Byte, Int32, Nullable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { DatabaseFacade } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { DbContext, DbContextOptionsBuilder, DbFunctions } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import type { ColumnBuilder, ComplexTypePropertyBuilder, IConventionEntityTypeBuilder, IConventionPropertyBuilder, OwnedNavigationTableBuilder, PropertyBuilder, SplitTableBuilder, TableBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Builders.js";
import type { ConfigurationSource, IConventionEntityType, IConventionEntityTypeMappingFragment, IConventionProperty, IConventionRelationalPropertyOverrides, IMutableEntityType, IMutableEntityTypeMappingFragment, IMutableProperty, IMutableRelationalPropertyOverrides, IReadOnlyEntityType, IReadOnlyEntityTypeMappingFragment, IReadOnlyProperty, IReadOnlyRelationalPropertyOverrides, ITable, StoreObjectIdentifier } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";

export abstract class SqliteComplexTypePropertyBuilderExtensions$instance {
    static hasSrid<TProperty>(propertyBuilder: ComplexTypePropertyBuilder<TProperty>, srid: int): ComplexTypePropertyBuilder<TProperty>;
    static hasSrid(propertyBuilder: ComplexTypePropertyBuilder, srid: int): ComplexTypePropertyBuilder;
    static useAutoincrement<TProperty>(propertyBuilder: ComplexTypePropertyBuilder<TProperty>): ComplexTypePropertyBuilder<TProperty>;
    static useAutoincrement(propertyBuilder: ComplexTypePropertyBuilder): ComplexTypePropertyBuilder;
}


export type SqliteComplexTypePropertyBuilderExtensions = SqliteComplexTypePropertyBuilderExtensions$instance;

export abstract class SqliteDatabaseFacadeExtensions$instance {
    static isSqlite(database: DatabaseFacade): boolean;
}


export type SqliteDatabaseFacadeExtensions = SqliteDatabaseFacadeExtensions$instance;

export abstract class SqliteDbContextOptionsBuilderExtensions$instance {
    static useSqlite<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, sqliteOptionsAction?: Action<SqliteDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static useSqlite<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connection: DbConnection, sqliteOptionsAction?: Action<SqliteDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static useSqlite<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connection: DbConnection, contextOwnsConnection: boolean, sqliteOptionsAction?: Action<SqliteDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static useSqlite<TContext extends DbContext>(optionsBuilder: DbContextOptionsBuilder<TContext>, connectionString: string, sqliteOptionsAction?: Action<SqliteDbContextOptionsBuilder>): DbContextOptionsBuilder<TContext>;
    static useSqlite(optionsBuilder: DbContextOptionsBuilder, sqliteOptionsAction?: Action<SqliteDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static useSqlite(optionsBuilder: DbContextOptionsBuilder, connection: DbConnection, sqliteOptionsAction?: Action<SqliteDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static useSqlite(optionsBuilder: DbContextOptionsBuilder, connection: DbConnection, contextOwnsConnection: boolean, sqliteOptionsAction?: Action<SqliteDbContextOptionsBuilder>): DbContextOptionsBuilder;
    static useSqlite(optionsBuilder: DbContextOptionsBuilder, connectionString: string, sqliteOptionsAction?: Action<SqliteDbContextOptionsBuilder>): DbContextOptionsBuilder;
}


export type SqliteDbContextOptionsBuilderExtensions = SqliteDbContextOptionsBuilderExtensions$instance;

export abstract class SqliteDbFunctionsExtensions$instance {
    static glob(_: DbFunctions, matchExpression: string, pattern: string): boolean;
    static hex(_: DbFunctions, bytes: byte[]): string;
    static substr(_: DbFunctions, bytes: byte[], startIndex: int, length: int): byte[];
    static substr(_: DbFunctions, bytes: byte[], startIndex: int): byte[];
    static unhex(_: DbFunctions, value: string, ignoreChars: string): byte[] | undefined;
    static unhex(_: DbFunctions, value: string): byte[] | undefined;
}


export type SqliteDbFunctionsExtensions = SqliteDbFunctionsExtensions$instance;

export abstract class SqliteEntityTypeBuilderExtensions$instance {
    static canUseSqlReturningClause(entityTypeBuilder: IConventionEntityTypeBuilder, useSqlReturningClause: Nullable<System_Internal.Boolean>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): boolean;
    static canUseSqlReturningClause(entityTypeBuilder: IConventionEntityTypeBuilder, useSqlReturningClause: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): boolean;
    static useSqlReturningClause(entityTypeBuilder: IConventionEntityTypeBuilder, useSqlReturningClause: Nullable<System_Internal.Boolean>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
    static useSqlReturningClause(entityTypeBuilder: IConventionEntityTypeBuilder, useSqlReturningClause: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): IConventionEntityTypeBuilder | undefined;
}


export type SqliteEntityTypeBuilderExtensions = SqliteEntityTypeBuilderExtensions$instance;

export abstract class SqliteEntityTypeExtensions$instance {
    static getUseSqlReturningClauseConfigurationSource(entityType: IConventionEntityType, storeObject: StoreObjectIdentifier): Nullable<ConfigurationSource>;
    static getUseSqlReturningClauseConfigurationSource(entityType: IConventionEntityType): Nullable<ConfigurationSource>;
    static isSqlReturningClauseUsed(entityType: IReadOnlyEntityType, storeObject: StoreObjectIdentifier): boolean;
    static isSqlReturningClauseUsed(entityType: IReadOnlyEntityType): boolean;
    static useSqlReturningClause(entityType: IConventionEntityType, useSqlReturningClause: Nullable<System_Internal.Boolean>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static useSqlReturningClause(entityType: IConventionEntityType, useSqlReturningClause: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static useSqlReturningClause(entityType: IMutableEntityType, useSqlReturningClause: Nullable<System_Internal.Boolean>, storeObject: StoreObjectIdentifier): void;
    static useSqlReturningClause(entityType: IMutableEntityType, useSqlReturningClause: Nullable<System_Internal.Boolean>): void;
}


export type SqliteEntityTypeExtensions = SqliteEntityTypeExtensions$instance;

export abstract class SqliteEntityTypeMappingFragmentExtensions$instance {
    static getUseSqlReturningClauseConfigurationSource(fragment: IConventionEntityTypeMappingFragment): Nullable<ConfigurationSource>;
    static isSqlReturningClauseUsed(fragment: IReadOnlyEntityTypeMappingFragment): boolean;
    static useSqlReturningClause(fragment: IConventionEntityTypeMappingFragment, useSqlReturningClause: Nullable<System_Internal.Boolean>, fromDataAnnotation?: boolean): Nullable<System_Internal.Boolean>;
    static useSqlReturningClause(fragment: IMutableEntityTypeMappingFragment, useSqlReturningClause: Nullable<System_Internal.Boolean>): void;
}


export type SqliteEntityTypeMappingFragmentExtensions = SqliteEntityTypeMappingFragmentExtensions$instance;

export abstract class SqlitePropertyBuilderExtensions$instance {
    static canSetSrid(propertyBuilder: IConventionPropertyBuilder, srid: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): boolean;
    static canSetValueGenerationStrategy(propertyBuilder: IConventionPropertyBuilder, strategy: Nullable<SqliteValueGenerationStrategy>, fromDataAnnotation?: boolean): boolean;
    static hasSrid(propertyBuilder: IConventionPropertyBuilder, srid: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static hasSrid(propertyBuilder: PropertyBuilder, srid: int): PropertyBuilder;
    static hasSrid<TProperty>(propertyBuilder: PropertyBuilder<TProperty>, srid: int): PropertyBuilder<TProperty>;
    static hasValueGenerationStrategy(propertyBuilder: IConventionPropertyBuilder, strategy: Nullable<SqliteValueGenerationStrategy>, fromDataAnnotation?: boolean): IConventionPropertyBuilder | undefined;
    static useAutoincrement(columnBuilder: ColumnBuilder): ColumnBuilder;
    static useAutoincrement(propertyBuilder: PropertyBuilder): PropertyBuilder;
    static useAutoincrement<TProperty>(propertyBuilder: PropertyBuilder<TProperty>): PropertyBuilder<TProperty>;
}


export type SqlitePropertyBuilderExtensions = SqlitePropertyBuilderExtensions$instance;

export abstract class SqlitePropertyExtensions$instance {
    static getDefaultValueGenerationStrategy(property: IReadOnlyProperty): SqliteValueGenerationStrategy;
    static getSrid(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): Nullable<System_Internal.Int32>;
    static getSrid(property: IReadOnlyProperty): Nullable<System_Internal.Int32>;
    static getSridConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static getValueGenerationStrategy(property: IReadOnlyProperty, storeObject: StoreObjectIdentifier): SqliteValueGenerationStrategy;
    static getValueGenerationStrategy(property: IReadOnlyProperty): SqliteValueGenerationStrategy;
    static getValueGenerationStrategy(overrides: IReadOnlyRelationalPropertyOverrides): Nullable<SqliteValueGenerationStrategy>;
    static getValueGenerationStrategyConfigurationSource(property: IConventionProperty, storeObject: StoreObjectIdentifier): Nullable<ConfigurationSource>;
    static getValueGenerationStrategyConfigurationSource(property: IConventionProperty): Nullable<ConfigurationSource>;
    static getValueGenerationStrategyConfigurationSource(overrides: IConventionRelationalPropertyOverrides): Nullable<ConfigurationSource>;
    static setSrid(property: IConventionProperty, value: Nullable<System_Internal.Int32>, fromDataAnnotation?: boolean): Nullable<System_Internal.Int32>;
    static setSrid(property: IMutableProperty, value: Nullable<System_Internal.Int32>): void;
    static setValueGenerationStrategy(property: IConventionProperty, value: Nullable<SqliteValueGenerationStrategy>, storeObject: StoreObjectIdentifier, fromDataAnnotation?: boolean): Nullable<SqliteValueGenerationStrategy>;
    static setValueGenerationStrategy(property: IConventionProperty, value: Nullable<SqliteValueGenerationStrategy>, fromDataAnnotation?: boolean): Nullable<SqliteValueGenerationStrategy>;
    static setValueGenerationStrategy(overrides: IConventionRelationalPropertyOverrides, value: Nullable<SqliteValueGenerationStrategy>, fromDataAnnotation?: boolean): Nullable<SqliteValueGenerationStrategy>;
    static setValueGenerationStrategy(property: IMutableProperty, value: Nullable<SqliteValueGenerationStrategy>, storeObject: StoreObjectIdentifier): void;
    static setValueGenerationStrategy(property: IMutableProperty, value: Nullable<SqliteValueGenerationStrategy>): void;
    static setValueGenerationStrategy(overrides: IMutableRelationalPropertyOverrides, value: Nullable<SqliteValueGenerationStrategy>): void;
}


export type SqlitePropertyExtensions = SqlitePropertyExtensions$instance;

export abstract class SqliteTableBuilderExtensions$instance {
    static useSqlReturningClause(tableBuilder: OwnedNavigationTableBuilder, useSqlReturningClause?: boolean): OwnedNavigationTableBuilder;
    static useSqlReturningClause(tableBuilder: SplitTableBuilder, useSqlReturningClause?: boolean): SplitTableBuilder;
    static useSqlReturningClause(tableBuilder: TableBuilder, useSqlReturningClause?: boolean): TableBuilder;
    static useSqlReturningClause<TOwnerEntity, TDependentEntity>(tableBuilder: OwnedNavigationTableBuilder<TOwnerEntity, TDependentEntity>, useSqlReturningClause?: boolean): OwnedNavigationTableBuilder<TOwnerEntity, TDependentEntity>;
    static useSqlReturningClause<TEntity>(tableBuilder: SplitTableBuilder<TEntity>, useSqlReturningClause?: boolean): SplitTableBuilder<TEntity>;
    static useSqlReturningClause<TEntity>(tableBuilder: TableBuilder<TEntity>, useSqlReturningClause?: boolean): TableBuilder<TEntity>;
}


export type SqliteTableBuilderExtensions = SqliteTableBuilderExtensions$instance;

export abstract class SqliteTableExtensions$instance {
    static isSqlReturningClauseUsed(table: ITable): boolean;
}


export type SqliteTableExtensions = SqliteTableExtensions$instance;

