// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Infrastructure
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Abstractions, Microsoft.EntityFrameworkCore.Relational, Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as Microsoft_EntityFrameworkCore_Sqlite_Infrastructure_Internal_Internal from "../../Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal/internal/index.js";
import type { SqliteOptionsExtension } from "../../Microsoft.EntityFrameworkCore.Sqlite.Infrastructure.Internal/internal/index.js";
import type { DbConnection } from "@tsonic/dotnet/System.Data.Common.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Object as ClrObject, Void } from "@tsonic/dotnet/System.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { IRelationalDbContextOptionsBuilderInfrastructure, RelationalDbContextOptionsBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { DbContextOptionsBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";

export interface SqliteDbContextOptionsBuilder$instance extends RelationalDbContextOptionsBuilder<SqliteDbContextOptionsBuilder, SqliteOptionsExtension> {
}


export const SqliteDbContextOptionsBuilder: {
    new(optionsBuilder: DbContextOptionsBuilder): SqliteDbContextOptionsBuilder;
};


export type SqliteDbContextOptionsBuilder = SqliteDbContextOptionsBuilder$instance;

export abstract class SpatialiteLoader$instance {
    static Load(connection: DbConnection): void;
    static TryLoad(connection: DbConnection): boolean;
}


export type SpatialiteLoader = SpatialiteLoader$instance;

