// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { DbConnection } from "@tsonic/dotnet/System.Data.Common.js";
import type { DbType } from "@tsonic/dotnet/System.Data.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, IAsyncDisposable, IDisposable, Int32, Nullable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { Expression } from "@tsonic/dotnet/System.Linq.Expressions.js";
import type { MethodInfo } from "@tsonic/dotnet/System.Reflection.js";
import type { StringBuilder } from "@tsonic/dotnet/System.Text.js";
import type { IDiagnosticsLogger } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";
import * as Microsoft_EntityFrameworkCore_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { IResettableService } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import type { DbLoggerCategory$Infrastructure } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import * as Microsoft_EntityFrameworkCore_Storage_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";
import type { ByteArrayTypeMapping, DateOnlyTypeMapping, DateTimeOffsetTypeMapping, DateTimeTypeMapping, DecimalTypeMapping, GuidTypeMapping, IDatabaseCreator, IDbContextTransactionManager, IRawSqlCommandBuilder, IRelationalConnection, IRelationalDatabaseCreator, IRelationalTransactionManager, IRelationalTypeMappingSource, ISqlGenerationHelper, ITransactionEnlistmentManager, ITypeMappingSource, JsonTypeMapping, RelationalConnection, RelationalConnectionDependencies, RelationalDatabaseCreator, RelationalDatabaseCreatorDependencies, RelationalSqlGenerationHelper, RelationalSqlGenerationHelperDependencies, RelationalTypeMapping, RelationalTypeMappingInfo, RelationalTypeMappingSource, RelationalTypeMappingSourceDependencies, StringTypeMapping, TimeOnlyTypeMapping, TypeMappingSourceDependencies, ULongTypeMapping } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export interface ISqliteRelationalConnection$instance extends IRelationalConnection, IRelationalTransactionManager, IDbContextTransactionManager, IResettableService, IDisposable, IAsyncDisposable {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Sqlite_Storage_Internal_ISqliteRelationalConnection: never;

    CreateReadOnlyConnection(): ISqliteRelationalConnection;
}


export interface ISqliteRelationalConnection$instance extends Microsoft_EntityFrameworkCore_Infrastructure_Internal.IResettableService, Microsoft_EntityFrameworkCore_Storage_Internal.IDbContextTransactionManager, Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalConnection, Microsoft_EntityFrameworkCore_Storage_Internal.IRelationalTransactionManager, System_Internal.IAsyncDisposable, System_Internal.IDisposable {}

export type ISqliteRelationalConnection = ISqliteRelationalConnection$instance;

export interface SqliteByteArrayTypeMapping$instance extends ByteArrayTypeMapping {
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
}


export const SqliteByteArrayTypeMapping: {
    new(storeType: string, dbType: Nullable<DbType>): SqliteByteArrayTypeMapping;
    readonly Default: SqliteByteArrayTypeMapping;
};


export type SqliteByteArrayTypeMapping = SqliteByteArrayTypeMapping$instance;

export interface SqliteDatabaseCreator$instance extends RelationalDatabaseCreator {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IDatabaseCreator: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalDatabaseCreator: never;

    Create(): void;
    Delete(): void;
    Exists(): boolean;
    HasTables(): boolean;
}


export const SqliteDatabaseCreator: {
    new(dependencies: RelationalDatabaseCreatorDependencies, connection: ISqliteRelationalConnection, rawSqlCommandBuilder: IRawSqlCommandBuilder): SqliteDatabaseCreator;
};


export type SqliteDatabaseCreator = SqliteDatabaseCreator$instance;

export interface SqliteDateOnlyTypeMapping$instance extends DateOnlyTypeMapping {
    readonly SqlLiteralFormatString: string;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
}


export const SqliteDateOnlyTypeMapping: {
    new(storeType: string, dbType: Nullable<DbType>): SqliteDateOnlyTypeMapping;
    readonly Default: SqliteDateOnlyTypeMapping;
};


export type SqliteDateOnlyTypeMapping = SqliteDateOnlyTypeMapping$instance;

export interface SqliteDateTimeOffsetTypeMapping$instance extends DateTimeOffsetTypeMapping {
    readonly SqlLiteralFormatString: string;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
}


export const SqliteDateTimeOffsetTypeMapping: {
    new(storeType: string, dbType: Nullable<DbType>): SqliteDateTimeOffsetTypeMapping;
    readonly Default: SqliteDateTimeOffsetTypeMapping;
};


export type SqliteDateTimeOffsetTypeMapping = SqliteDateTimeOffsetTypeMapping$instance;

export interface SqliteDateTimeTypeMapping$instance extends DateTimeTypeMapping {
    readonly SqlLiteralFormatString: string;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
}


export const SqliteDateTimeTypeMapping: {
    new(storeType: string, dbType: Nullable<DbType>): SqliteDateTimeTypeMapping;
    readonly Default: SqliteDateTimeTypeMapping;
};


export type SqliteDateTimeTypeMapping = SqliteDateTimeTypeMapping$instance;

export interface SqliteDecimalTypeMapping$instance extends DecimalTypeMapping {
    readonly SqlLiteralFormatString: string;
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
}


export const SqliteDecimalTypeMapping: {
    new(storeType: string, dbType: Nullable<DbType>): SqliteDecimalTypeMapping;
    readonly Default: SqliteDecimalTypeMapping;
};


export type SqliteDecimalTypeMapping = SqliteDecimalTypeMapping$instance;

export interface SqliteGuidTypeMapping$instance extends GuidTypeMapping {
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqliteGuidTypeMapping: {
    new(storeType: string, dbType: Nullable<DbType>): SqliteGuidTypeMapping;
    readonly Default: SqliteGuidTypeMapping;
};


export type SqliteGuidTypeMapping = SqliteGuidTypeMapping$instance;

export interface SqliteJsonTypeMapping$instance extends JsonTypeMapping {
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    CustomizeDataReaderExpression(expression: Expression): Expression;
    EscapeSqlLiteral(literal: string): string;
    GenerateNonNullSqlLiteral(value: unknown): string;
    GetDataReaderMethod(): MethodInfo;
}


export const SqliteJsonTypeMapping: {
    new(storeType: string): SqliteJsonTypeMapping;
    readonly Default: SqliteJsonTypeMapping;
};


export type SqliteJsonTypeMapping = SqliteJsonTypeMapping$instance;

export interface SqliteRelationalConnection$instance extends RelationalConnection {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Infrastructure_IResettableService: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Sqlite_Storage_Internal_ISqliteRelationalConnection: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IDbContextTransactionManager: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalConnection: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalTransactionManager: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_ITransactionEnlistmentManager: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    CreateDbConnection(): DbConnection;
    CreateReadOnlyConnection(): ISqliteRelationalConnection;
}


export const SqliteRelationalConnection: {
    new(dependencies: RelationalConnectionDependencies, rawSqlCommandBuilder: IRawSqlCommandBuilder, logger: IDiagnosticsLogger<DbLoggerCategory$Infrastructure>): SqliteRelationalConnection;
};


export interface __SqliteRelationalConnection$views {
    As_ISqliteRelationalConnection(): ISqliteRelationalConnection$instance;
}

export interface SqliteRelationalConnection$instance extends ISqliteRelationalConnection$instance, Microsoft_EntityFrameworkCore_Storage_Internal.ITransactionEnlistmentManager {}

export type SqliteRelationalConnection = SqliteRelationalConnection$instance & __SqliteRelationalConnection$views;


export interface SqliteSqlGenerationHelper$instance extends RelationalSqlGenerationHelper {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_ISqlGenerationHelper: never;

    readonly StartTransactionStatement: string;
    DelimitIdentifier(name: string, schema: string): string;
    DelimitIdentifier(builder: StringBuilder, name: string, schema: string): void;
}


export const SqliteSqlGenerationHelper: {
    new(dependencies: RelationalSqlGenerationHelperDependencies): SqliteSqlGenerationHelper;
};


export type SqliteSqlGenerationHelper = SqliteSqlGenerationHelper$instance;

export interface SqliteStringTypeMapping$instance extends StringTypeMapping {
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqliteStringTypeMapping: {
    new(storeType: string, dbType: Nullable<DbType>, unicode: boolean, size: Nullable<System_Internal.Int32>): SqliteStringTypeMapping;
    readonly Default: SqliteStringTypeMapping;
};


export type SqliteStringTypeMapping = SqliteStringTypeMapping$instance;

export interface SqliteTimeOnlyTypeMapping$instance extends TimeOnlyTypeMapping {
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqliteTimeOnlyTypeMapping: {
    new(storeType: string, dbType: Nullable<DbType>): SqliteTimeOnlyTypeMapping;
    readonly Default: SqliteTimeOnlyTypeMapping;
};


export type SqliteTimeOnlyTypeMapping = SqliteTimeOnlyTypeMapping$instance;

export interface SqliteTypeMappingSource$instance extends RelationalTypeMappingSource {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_IRelationalTypeMappingSource: never;
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Storage_ITypeMappingSource: never;

    FindMapping(mappingInfo: RelationalTypeMappingInfo): RelationalTypeMapping | undefined;
}


export const SqliteTypeMappingSource: {
    new(dependencies: TypeMappingSourceDependencies, relationalDependencies: RelationalTypeMappingSourceDependencies): SqliteTypeMappingSource;
    IsSpatialiteType(columnType: string): boolean;
};


export type SqliteTypeMappingSource = SqliteTypeMappingSource$instance;

export interface SqliteULongTypeMapping$instance extends ULongTypeMapping {
    Clone(parameters: RelationalTypeMapping_RelationalTypeMappingParameters): RelationalTypeMapping;
    GenerateNonNullSqlLiteral(value: unknown): string;
}


export const SqliteULongTypeMapping: {
    new(storeType: string, dbType: Nullable<DbType>): SqliteULongTypeMapping;
    readonly Default: SqliteULongTypeMapping;
};


export type SqliteULongTypeMapping = SqliteULongTypeMapping$instance;

