// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Query.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { IEnumerable, IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { DbCommand } from "@tsonic/dotnet/System.Data.Common.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, Type, Void } from "@tsonic/dotnet/System.js";
import type { BinaryExpression, Expression, ExpressionVisitor, LambdaExpression, MethodCallExpression, UnaryExpression } from "@tsonic/dotnet/System.Linq.Expressions.js";
import type { MemberInfo, MethodInfo } from "@tsonic/dotnet/System.Reflection.js";
import type { IDiagnosticsLogger } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";
import type { DbLoggerCategory$Query } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import type { IProperty } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import * as Microsoft_EntityFrameworkCore_Query_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.js";
import type { EnumerableExpression, ExpressionPrinter, IAggregateMethodCallTranslator, IAggregateMethodCallTranslatorProvider, IMemberTranslator, IMemberTranslatorProvider, IMethodCallTranslator, IMethodCallTranslatorProvider, IPrintableExpression, IQueryableMethodTranslatingExpressionVisitorFactory, IQueryCompilationContextFactory, IQuerySqlGeneratorFactory, IQueryTranslationPostprocessorFactory, IRelationalParameterBasedSqlProcessorFactory, IRelationalQueryStringFactory, IRelationalQuotableExpression, IRelationalSqlTranslatingExpressionVisitorFactory, ISqlExpressionFactory, JsonQueryExpression, ParametersCacheDecorator, PathSegment, QueryableMethodTranslatingExpressionVisitor, QueryableMethodTranslatingExpressionVisitorDependencies, QueryCompilationContext, QueryCompilationContextDependencies, QueryContext, QuerySqlGenerator, QuerySqlGeneratorDependencies, QueryTranslationPostprocessor, QueryTranslationPostprocessorDependencies, RelationalAggregateMethodCallTranslatorProvider, RelationalAggregateMethodCallTranslatorProviderDependencies, RelationalMemberTranslatorProvider, RelationalMemberTranslatorProviderDependencies, RelationalMethodCallTranslatorProvider, RelationalMethodCallTranslatorProviderDependencies, RelationalParameterBasedSqlProcessor, RelationalParameterBasedSqlProcessorDependencies, RelationalParameterBasedSqlProcessorParameters, RelationalQueryableMethodTranslatingExpressionVisitor, RelationalQueryableMethodTranslatingExpressionVisitorDependencies, RelationalQueryCompilationContext, RelationalQueryCompilationContextDependencies, RelationalQueryTranslationPostprocessor, RelationalQueryTranslationPostprocessorDependencies, RelationalSqlTranslatingExpressionVisitor, RelationalSqlTranslatingExpressionVisitorDependencies, RelationalTypeMappingPostprocessor, ShapedQueryExpression, SqlExpressionFactory, SqlExpressionFactoryDependencies, SqlNullabilityProcessor } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.js";
import * as Microsoft_EntityFrameworkCore_Query_SqlExpressions_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.SqlExpressions.js";
import type { ITableBasedExpression, JsonScalarExpression, SelectExpression, SetOperationBase, SqlBinaryExpression, SqlConstantExpression, SqlExpression, SqlFunctionExpression, SqlParameterExpression, SqlUnaryExpression, TableExpressionBase, TableValuedFunctionExpression } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.SqlExpressions.js";
import type { IRelationalTypeMappingSource, RelationalTypeMapping } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export interface GlobExpression$instance extends SqlExpression {
    readonly Match: SqlExpression;
    readonly Pattern: SqlExpression;
    readonly TypeMapping: RelationalTypeMapping;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    Update(match: SqlExpression, pattern: SqlExpression): GlobExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const GlobExpression: {
    new(match: SqlExpression, pattern: SqlExpression, typeMapping: RelationalTypeMapping): GlobExpression;
};


export type GlobExpression = GlobExpression$instance;

export interface JsonEachExpression$instance extends TableValuedFunctionExpression {
    readonly JsonExpression: SqlExpression;
    readonly Path: IReadOnlyList<PathSegment> | undefined;
    Clone(alias: string, cloningExpressionVisitor: ExpressionVisitor): TableExpressionBase;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    Update(jsonExpression: SqlExpression, path: IReadOnlyList<PathSegment>): JsonEachExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
    WithAlias(newAlias: string): JsonEachExpression;
}


export const JsonEachExpression: {
    new(alias: string, jsonExpression: SqlExpression, path: IReadOnlyList<PathSegment>): JsonEachExpression;
};


export type JsonEachExpression = JsonEachExpression$instance;

export interface RegexpExpression$instance extends SqlExpression {
    readonly Match: SqlExpression;
    readonly Pattern: SqlExpression;
    readonly TypeMapping: RelationalTypeMapping;
    Equals(obj: unknown): boolean;
    GetHashCode(): int;
    Print(expressionPrinter: ExpressionPrinter): void;
    Quote(): Expression;
    Update(match: SqlExpression, pattern: SqlExpression): RegexpExpression;
    VisitChildren(visitor: ExpressionVisitor): Expression;
}


export const RegexpExpression: {
    new(match: SqlExpression, pattern: SqlExpression, typeMapping: RelationalTypeMapping): RegexpExpression;
};


export type RegexpExpression = RegexpExpression$instance;

export interface SqliteAggregateMethodCallTranslatorProvider$instance extends RelationalAggregateMethodCallTranslatorProvider {
}


export const SqliteAggregateMethodCallTranslatorProvider: {
    new(dependencies: RelationalAggregateMethodCallTranslatorProviderDependencies): SqliteAggregateMethodCallTranslatorProvider;
};


export type SqliteAggregateMethodCallTranslatorProvider = SqliteAggregateMethodCallTranslatorProvider$instance;

export interface SqliteByteArrayMethodTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteByteArrayMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteByteArrayMethodTranslator;
};


export type SqliteByteArrayMethodTranslator = SqliteByteArrayMethodTranslator$instance;

export interface SqliteCharMethodTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteCharMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteCharMethodTranslator;
};


export type SqliteCharMethodTranslator = SqliteCharMethodTranslator$instance;

export interface SqliteDateOnlyMemberTranslator$instance {
    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteDateOnlyMemberTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteDateOnlyMemberTranslator;
};


export type SqliteDateOnlyMemberTranslator = SqliteDateOnlyMemberTranslator$instance;

export interface SqliteDateOnlyMethodTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteDateOnlyMethodTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteDateOnlyMethodTranslator;
};


export type SqliteDateOnlyMethodTranslator = SqliteDateOnlyMethodTranslator$instance;

export interface SqliteDateTimeMemberTranslator$instance {
    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteDateTimeMemberTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteDateTimeMemberTranslator;
};


export type SqliteDateTimeMemberTranslator = SqliteDateTimeMemberTranslator$instance;

export interface SqliteDateTimeMethodTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteDateTimeMethodTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteDateTimeMethodTranslator;
};


export type SqliteDateTimeMethodTranslator = SqliteDateTimeMethodTranslator$instance;

export interface SqliteGlobMethodTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteGlobMethodTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteGlobMethodTranslator;
};


export type SqliteGlobMethodTranslator = SqliteGlobMethodTranslator$instance;

export interface SqliteHexMethodTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteHexMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteHexMethodTranslator;
};


export type SqliteHexMethodTranslator = SqliteHexMethodTranslator$instance;

export interface SqliteMathTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteMathTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteMathTranslator;
};


export type SqliteMathTranslator = SqliteMathTranslator$instance;

export interface SqliteMemberTranslatorProvider$instance extends RelationalMemberTranslatorProvider {
}


export const SqliteMemberTranslatorProvider: {
    new(dependencies: RelationalMemberTranslatorProviderDependencies): SqliteMemberTranslatorProvider;
};


export type SqliteMemberTranslatorProvider = SqliteMemberTranslatorProvider$instance;

export interface SqliteMethodCallTranslatorProvider$instance extends RelationalMethodCallTranslatorProvider {
}


export const SqliteMethodCallTranslatorProvider: {
    new(dependencies: RelationalMethodCallTranslatorProviderDependencies): SqliteMethodCallTranslatorProvider;
};


export type SqliteMethodCallTranslatorProvider = SqliteMethodCallTranslatorProvider$instance;

export interface SqliteObjectToStringTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteObjectToStringTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteObjectToStringTranslator;
};


export type SqliteObjectToStringTranslator = SqliteObjectToStringTranslator$instance;

export interface SqliteParameterBasedSqlProcessor$instance extends RelationalParameterBasedSqlProcessor {
    ProcessSqlNullability(queryExpression: Expression, parametersDecorator: ParametersCacheDecorator): Expression;
}


export const SqliteParameterBasedSqlProcessor: {
    new(dependencies: RelationalParameterBasedSqlProcessorDependencies, parameters: RelationalParameterBasedSqlProcessorParameters): SqliteParameterBasedSqlProcessor;
};


export type SqliteParameterBasedSqlProcessor = SqliteParameterBasedSqlProcessor$instance;

export interface SqliteParameterBasedSqlProcessorFactory$instance {
    Create(parameters: RelationalParameterBasedSqlProcessorParameters): RelationalParameterBasedSqlProcessor;
}


export const SqliteParameterBasedSqlProcessorFactory: {
    new(dependencies: RelationalParameterBasedSqlProcessorDependencies): SqliteParameterBasedSqlProcessorFactory;
};


export type SqliteParameterBasedSqlProcessorFactory = SqliteParameterBasedSqlProcessorFactory$instance;

export interface SqliteQueryableAggregateMethodTranslator$instance {
    Translate(method: MethodInfo, source: EnumerableExpression, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteQueryableAggregateMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteQueryableAggregateMethodTranslator;
};


export type SqliteQueryableAggregateMethodTranslator = SqliteQueryableAggregateMethodTranslator$instance;

export interface SqliteQueryableMethodTranslatingExpressionVisitor$instance extends RelationalQueryableMethodTranslatingExpressionVisitor {
    CreateSubqueryVisitor(): QueryableMethodTranslatingExpressionVisitor;
    GenerateJsonPartialUpdateSetter(target: Expression, value: SqlExpression, existingSetterValue: SqlExpression): SqlExpression | undefined;
    IsNaturallyOrdered(selectExpression: SelectExpression): boolean;
    TransformJsonQueryToTable(jsonQueryExpression: JsonQueryExpression): ShapedQueryExpression;
    TranslateAny(source: ShapedQueryExpression, predicate: LambdaExpression): ShapedQueryExpression | undefined;
    TranslateCount(source: ShapedQueryExpression, predicate: LambdaExpression): ShapedQueryExpression | undefined;
    TranslateElementAtOrDefault(source: ShapedQueryExpression, index: Expression, returnDefault: boolean): ShapedQueryExpression | undefined;
    TranslateOrderBy(source: ShapedQueryExpression, keySelector: LambdaExpression, ascending: boolean): ShapedQueryExpression | undefined;
    TranslatePrimitiveCollection(sqlExpression: SqlExpression, property: IProperty, tableAlias: string): ShapedQueryExpression | undefined;
    TranslateThenBy(source: ShapedQueryExpression, keySelector: LambdaExpression, ascending: boolean): ShapedQueryExpression | undefined;
    TrySerializeScalarToJson(target: JsonScalarExpression, value: SqlExpression, jsonValue: SqlExpression): boolean;
}


export const SqliteQueryableMethodTranslatingExpressionVisitor: {
    new(dependencies: QueryableMethodTranslatingExpressionVisitorDependencies, relationalDependencies: RelationalQueryableMethodTranslatingExpressionVisitorDependencies, queryCompilationContext: RelationalQueryCompilationContext): SqliteQueryableMethodTranslatingExpressionVisitor;
    readonly JsonEachKeyColumnName: string;
    readonly JsonEachValueColumnName: string;
    ApplyJsonSqlConversion(expression: SqlExpression, sqlExpressionFactory: SqliteSqlExpressionFactory, typeMapping: RelationalTypeMapping, isNullable: boolean): SqlExpression;
};


export type SqliteQueryableMethodTranslatingExpressionVisitor = SqliteQueryableMethodTranslatingExpressionVisitor$instance;

export interface SqliteQueryableMethodTranslatingExpressionVisitorFactory$instance {
    readonly Dependencies: QueryableMethodTranslatingExpressionVisitorDependencies;
    readonly RelationalDependencies: RelationalQueryableMethodTranslatingExpressionVisitorDependencies;
    Create(queryCompilationContext: QueryCompilationContext): QueryableMethodTranslatingExpressionVisitor;
}


export const SqliteQueryableMethodTranslatingExpressionVisitorFactory: {
    new(dependencies: QueryableMethodTranslatingExpressionVisitorDependencies, relationalDependencies: RelationalQueryableMethodTranslatingExpressionVisitorDependencies): SqliteQueryableMethodTranslatingExpressionVisitorFactory;
};


export type SqliteQueryableMethodTranslatingExpressionVisitorFactory = SqliteQueryableMethodTranslatingExpressionVisitorFactory$instance;

export interface SqliteQueryCompilationContext$instance extends RelationalQueryCompilationContext {
    readonly SupportsPrecompiledQuery: boolean;
}


export const SqliteQueryCompilationContext: {
    new(dependencies: QueryCompilationContextDependencies, relationalDependencies: RelationalQueryCompilationContextDependencies, async: boolean): SqliteQueryCompilationContext;
    new(dependencies: QueryCompilationContextDependencies, relationalDependencies: RelationalQueryCompilationContextDependencies, async: boolean, precompiling: boolean): SqliteQueryCompilationContext;
};


export type SqliteQueryCompilationContext = SqliteQueryCompilationContext$instance;

export interface SqliteQueryCompilationContextFactory$instance {
    readonly Dependencies: QueryCompilationContextDependencies;
    readonly RelationalDependencies: RelationalQueryCompilationContextDependencies;
    Create(async: boolean): QueryCompilationContext;
    CreatePrecompiled(async: boolean): QueryCompilationContext;
}


export const SqliteQueryCompilationContextFactory: {
    new(dependencies: QueryCompilationContextDependencies, relationalDependencies: RelationalQueryCompilationContextDependencies): SqliteQueryCompilationContextFactory;
};


export type SqliteQueryCompilationContextFactory = SqliteQueryCompilationContextFactory$instance;

export interface SqliteQuerySqlGenerator$instance extends QuerySqlGenerator {
    GenerateJsonEach(jsonEachExpression: JsonEachExpression): void;
    GenerateLimitOffset(selectExpression: SelectExpression): void;
    GenerateSetOperationOperand(setOperation: SetOperationBase, operand: SelectExpression): void;
    GetOperator(binaryExpression: SqlBinaryExpression): string;
    TryGetOperatorInfo(expression: SqlExpression, precedence: int, isAssociative: boolean): boolean;
    VisitExtension(extensionExpression: Expression): Expression;
    VisitJsonScalar(jsonScalarExpression: JsonScalarExpression): Expression;
    VisitSqlConstant(sqlConstantExpression: SqlConstantExpression): Expression;
    VisitSqlUnary(sqlUnaryExpression: SqlUnaryExpression): Expression;
}


export const SqliteQuerySqlGenerator: {
    new(dependencies: QuerySqlGeneratorDependencies): SqliteQuerySqlGenerator;
};


export type SqliteQuerySqlGenerator = SqliteQuerySqlGenerator$instance;

export interface SqliteQuerySqlGeneratorFactory$instance {
    readonly Dependencies: QuerySqlGeneratorDependencies;
    Create(): QuerySqlGenerator;
}


export const SqliteQuerySqlGeneratorFactory: {
    new(dependencies: QuerySqlGeneratorDependencies): SqliteQuerySqlGeneratorFactory;
};


export type SqliteQuerySqlGeneratorFactory = SqliteQuerySqlGeneratorFactory$instance;

export interface SqliteQueryStringFactory$instance {
    Create(command: DbCommand): string;
}


export const SqliteQueryStringFactory: {
    new(typeMapper: IRelationalTypeMappingSource): SqliteQueryStringFactory;
};


export type SqliteQueryStringFactory = SqliteQueryStringFactory$instance;

export interface SqliteQueryTranslationPostprocessor$instance extends RelationalQueryTranslationPostprocessor {
    Process(query: Expression): Expression;
    ProcessTypeMappings(expression: Expression): Expression;
}


export const SqliteQueryTranslationPostprocessor: {
    new(dependencies: QueryTranslationPostprocessorDependencies, relationalDependencies: RelationalQueryTranslationPostprocessorDependencies, queryCompilationContext: RelationalQueryCompilationContext): SqliteQueryTranslationPostprocessor;
};


export type SqliteQueryTranslationPostprocessor = SqliteQueryTranslationPostprocessor$instance;

export interface SqliteQueryTranslationPostprocessorFactory$instance {
    readonly Dependencies: QueryTranslationPostprocessorDependencies;
    readonly RelationalDependencies: RelationalQueryTranslationPostprocessorDependencies;
    Create(queryCompilationContext: QueryCompilationContext): QueryTranslationPostprocessor;
}


export const SqliteQueryTranslationPostprocessorFactory: {
    new(dependencies: QueryTranslationPostprocessorDependencies, relationalDependencies: RelationalQueryTranslationPostprocessorDependencies): SqliteQueryTranslationPostprocessorFactory;
};


export type SqliteQueryTranslationPostprocessorFactory = SqliteQueryTranslationPostprocessorFactory$instance;

export interface SqliteRandomTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteRandomTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteRandomTranslator;
};


export type SqliteRandomTranslator = SqliteRandomTranslator$instance;

export interface SqliteRegexMethodTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteRegexMethodTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteRegexMethodTranslator;
};


export type SqliteRegexMethodTranslator = SqliteRegexMethodTranslator$instance;

export interface SqliteSqlExpressionFactory$instance extends SqlExpressionFactory {
    ApplyTypeMapping(sqlExpression: SqlExpression, typeMapping: RelationalTypeMapping): SqlExpression | undefined;
    Date(returnType: Type, timestring: SqlExpression, modifiers?: IEnumerable<SqlExpression>, typeMapping?: RelationalTypeMapping): SqlExpression;
    Glob(match: SqlExpression, pattern: SqlExpression): GlobExpression;
    Regexp(match: SqlExpression, pattern: SqlExpression): RegexpExpression;
    Strftime(returnType: Type, format: string, timestring: SqlExpression, modifiers?: IEnumerable<SqlExpression>, typeMapping?: RelationalTypeMapping): SqlExpression;
}


export const SqliteSqlExpressionFactory: {
    new(dependencies: SqlExpressionFactoryDependencies): SqliteSqlExpressionFactory;
};


export type SqliteSqlExpressionFactory = SqliteSqlExpressionFactory$instance;

export interface SqliteSqlNullabilityProcessor$instance extends SqlNullabilityProcessor {
    IsCollectionTable(table: TableExpressionBase, collection: Expression): boolean;
    UpdateParameterCollection(table: TableExpressionBase, newCollectionParameter: SqlParameterExpression): TableExpressionBase;
    VisitCustomSqlExpression(sqlExpression: SqlExpression, allowOptimizedExpansion: boolean, nullable: boolean): SqlExpression;
    VisitGlob(globExpression: GlobExpression, allowOptimizedExpansion: boolean, nullable: boolean): SqlExpression;
    VisitRegexp(regexpExpression: RegexpExpression, allowOptimizedExpansion: boolean, nullable: boolean): SqlExpression;
    VisitSqlFunction(sqlFunctionExpression: SqlFunctionExpression, allowOptimizedExpansion: boolean, nullable: boolean): SqlExpression;
}


export const SqliteSqlNullabilityProcessor: {
    new(dependencies: RelationalParameterBasedSqlProcessorDependencies, parameters: RelationalParameterBasedSqlProcessorParameters): SqliteSqlNullabilityProcessor;
};


export type SqliteSqlNullabilityProcessor = SqliteSqlNullabilityProcessor$instance;

export interface SqliteSqlTranslatingExpressionVisitor$instance extends RelationalSqlTranslatingExpressionVisitor {
    GenerateGreatest(expressions: IReadOnlyList<SqlExpression>, resultType: Type): SqlExpression;
    GenerateLeast(expressions: IReadOnlyList<SqlExpression>, resultType: Type): SqlExpression;
    VisitBinary(binaryExpression: BinaryExpression): Expression;
    VisitMethodCall(methodCallExpression: MethodCallExpression): Expression;
    VisitUnary(unaryExpression: UnaryExpression): Expression;
}


export const SqliteSqlTranslatingExpressionVisitor: {
    new(dependencies: RelationalSqlTranslatingExpressionVisitorDependencies, queryCompilationContext: QueryCompilationContext, queryableMethodTranslatingExpressionVisitor: QueryableMethodTranslatingExpressionVisitor): SqliteSqlTranslatingExpressionVisitor;
    ConstructLikePatternParameter(queryContext: QueryContext, baseParameterName: string, startsWith: boolean): string | undefined;
};


export type SqliteSqlTranslatingExpressionVisitor = SqliteSqlTranslatingExpressionVisitor$instance;

export interface SqliteSqlTranslatingExpressionVisitorFactory$instance {
    readonly Dependencies: RelationalSqlTranslatingExpressionVisitorDependencies;
    Create(queryCompilationContext: QueryCompilationContext, queryableMethodTranslatingExpressionVisitor: QueryableMethodTranslatingExpressionVisitor): RelationalSqlTranslatingExpressionVisitor;
}


export const SqliteSqlTranslatingExpressionVisitorFactory: {
    new(dependencies: RelationalSqlTranslatingExpressionVisitorDependencies): SqliteSqlTranslatingExpressionVisitorFactory;
};


export type SqliteSqlTranslatingExpressionVisitorFactory = SqliteSqlTranslatingExpressionVisitorFactory$instance;

export interface SqliteStringAggregateMethodTranslator$instance {
    Translate(method: MethodInfo, source: EnumerableExpression, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteStringAggregateMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteStringAggregateMethodTranslator;
};


export type SqliteStringAggregateMethodTranslator = SqliteStringAggregateMethodTranslator$instance;

export interface SqliteStringLengthTranslator$instance {
    Translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteStringLengthTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteStringLengthTranslator;
};


export type SqliteStringLengthTranslator = SqliteStringLengthTranslator$instance;

export interface SqliteStringMethodTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteStringMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteStringMethodTranslator;
};


export type SqliteStringMethodTranslator = SqliteStringMethodTranslator$instance;

export interface SqliteSubstrMethodTranslator$instance {
    Translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteSubstrMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteSubstrMethodTranslator;
};


export type SqliteSubstrMethodTranslator = SqliteSubstrMethodTranslator$instance;

export interface SqliteTypeMappingPostprocessor$instance extends RelationalTypeMappingPostprocessor {
    ApplyTypeMappingsOnJsonEachExpression(jsonEachExpression: JsonEachExpression, inferredTypeMapping: RelationalTypeMapping): JsonEachExpression;
    VisitExtension(expression: Expression): Expression;
}


export const SqliteTypeMappingPostprocessor: {
    new(dependencies: QueryTranslationPostprocessorDependencies, relationalDependencies: RelationalQueryTranslationPostprocessorDependencies, queryCompilationContext: RelationalQueryCompilationContext): SqliteTypeMappingPostprocessor;
};


export type SqliteTypeMappingPostprocessor = SqliteTypeMappingPostprocessor$instance;

