// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Query.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IEnumerable, IReadOnlyList } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { DbCommand } from "@tsonic/dotnet/System.Data.Common.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int32, Object as ClrObject, String as ClrString, Type } from "@tsonic/dotnet/System.js";
import type { Expression, ExpressionVisitor } from "@tsonic/dotnet/System.Linq.Expressions.js";
import type { MemberInfo, MethodInfo } from "@tsonic/dotnet/System.Reflection.js";
import type { IDiagnosticsLogger } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";
import type { DbLoggerCategory$Query } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import * as Microsoft_EntityFrameworkCore_Query_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.js";
import type { EnumerableExpression, IAggregateMethodCallTranslator, IAggregateMethodCallTranslatorProvider, IMemberTranslator, IMemberTranslatorProvider, IMethodCallTranslator, IMethodCallTranslatorProvider, IPrintableExpression, IQueryableMethodTranslatingExpressionVisitorFactory, IQueryCompilationContextFactory, IQuerySqlGeneratorFactory, IQueryTranslationPostprocessorFactory, IRelationalParameterBasedSqlProcessorFactory, IRelationalQueryStringFactory, IRelationalQuotableExpression, IRelationalSqlTranslatingExpressionVisitorFactory, ISqlExpressionFactory, PathSegment, QueryableMethodTranslatingExpressionVisitor, QueryableMethodTranslatingExpressionVisitorDependencies, QueryCompilationContext, QueryCompilationContextDependencies, QueryContext, QuerySqlGenerator, QuerySqlGeneratorDependencies, QueryTranslationPostprocessor, QueryTranslationPostprocessorDependencies, RelationalAggregateMethodCallTranslatorProvider, RelationalAggregateMethodCallTranslatorProviderDependencies, RelationalMemberTranslatorProvider, RelationalMemberTranslatorProviderDependencies, RelationalMethodCallTranslatorProvider, RelationalMethodCallTranslatorProviderDependencies, RelationalParameterBasedSqlProcessor, RelationalParameterBasedSqlProcessorDependencies, RelationalParameterBasedSqlProcessorParameters, RelationalQueryableMethodTranslatingExpressionVisitor, RelationalQueryableMethodTranslatingExpressionVisitorDependencies, RelationalQueryCompilationContext, RelationalQueryCompilationContextDependencies, RelationalQueryTranslationPostprocessor, RelationalQueryTranslationPostprocessorDependencies, RelationalSqlTranslatingExpressionVisitor, RelationalSqlTranslatingExpressionVisitorDependencies, RelationalTypeMappingPostprocessor, SqlExpressionFactory, SqlExpressionFactoryDependencies, SqlNullabilityProcessor } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.js";
import * as Microsoft_EntityFrameworkCore_Query_SqlExpressions_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.SqlExpressions.js";
import type { ITableBasedExpression, SqlExpression, TableExpressionBase, TableValuedFunctionExpression } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Query.SqlExpressions.js";
import type { IRelationalTypeMappingSource, RelationalTypeMapping } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export interface GlobExpression$instance extends SqlExpression {
    readonly match: SqlExpression;
    readonly pattern: SqlExpression;
    readonly typeMapping: RelationalTypeMapping;
    equals(obj: unknown): boolean;
    getHashCode(): int;
    quote(): Expression;
    update(match: SqlExpression, pattern: SqlExpression): GlobExpression;
}


export const GlobExpression: {
    new(match: SqlExpression, pattern: SqlExpression, typeMapping: RelationalTypeMapping): GlobExpression;
};


export type GlobExpression = GlobExpression$instance;

export interface JsonEachExpression$instance extends TableValuedFunctionExpression {
    readonly jsonExpression: SqlExpression;
    readonly path: IReadOnlyList<PathSegment> | undefined;
    clone(alias: string, cloningExpressionVisitor: ExpressionVisitor): TableExpressionBase;
    equals(obj: unknown): boolean;
    getHashCode(): int;
    quote(): Expression;
    update(jsonExpression: SqlExpression, path: IReadOnlyList<PathSegment>): JsonEachExpression;
    withAlias(newAlias: string): JsonEachExpression;
}


export const JsonEachExpression: {
    new(alias: string, jsonExpression: SqlExpression, path: IReadOnlyList<PathSegment>): JsonEachExpression;
};


export type JsonEachExpression = JsonEachExpression$instance;

export interface RegexpExpression$instance extends SqlExpression {
    readonly match: SqlExpression;
    readonly pattern: SqlExpression;
    readonly typeMapping: RelationalTypeMapping;
    equals(obj: unknown): boolean;
    getHashCode(): int;
    quote(): Expression;
    update(match: SqlExpression, pattern: SqlExpression): RegexpExpression;
}


export const RegexpExpression: {
    new(match: SqlExpression, pattern: SqlExpression, typeMapping: RelationalTypeMapping): RegexpExpression;
};


export type RegexpExpression = RegexpExpression$instance;

export interface SqliteAggregateMethodCallTranslatorProvider$instance extends RelationalAggregateMethodCallTranslatorProvider {
}


export const SqliteAggregateMethodCallTranslatorProvider: {
    new(dependencies: RelationalAggregateMethodCallTranslatorProviderDependencies): SqliteAggregateMethodCallTranslatorProvider;
};


export type SqliteAggregateMethodCallTranslatorProvider = SqliteAggregateMethodCallTranslatorProvider$instance;

export interface SqliteByteArrayMethodTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteByteArrayMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteByteArrayMethodTranslator;
};


export type SqliteByteArrayMethodTranslator = SqliteByteArrayMethodTranslator$instance;

export interface SqliteCharMethodTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteCharMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteCharMethodTranslator;
};


export type SqliteCharMethodTranslator = SqliteCharMethodTranslator$instance;

export interface SqliteDateOnlyMemberTranslator$instance {
    translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteDateOnlyMemberTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteDateOnlyMemberTranslator;
};


export type SqliteDateOnlyMemberTranslator = SqliteDateOnlyMemberTranslator$instance;

export interface SqliteDateOnlyMethodTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteDateOnlyMethodTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteDateOnlyMethodTranslator;
};


export type SqliteDateOnlyMethodTranslator = SqliteDateOnlyMethodTranslator$instance;

export interface SqliteDateTimeMemberTranslator$instance {
    translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteDateTimeMemberTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteDateTimeMemberTranslator;
};


export type SqliteDateTimeMemberTranslator = SqliteDateTimeMemberTranslator$instance;

export interface SqliteDateTimeMethodTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteDateTimeMethodTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteDateTimeMethodTranslator;
};


export type SqliteDateTimeMethodTranslator = SqliteDateTimeMethodTranslator$instance;

export interface SqliteGlobMethodTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteGlobMethodTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteGlobMethodTranslator;
};


export type SqliteGlobMethodTranslator = SqliteGlobMethodTranslator$instance;

export interface SqliteHexMethodTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteHexMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteHexMethodTranslator;
};


export type SqliteHexMethodTranslator = SqliteHexMethodTranslator$instance;

export interface SqliteMathTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteMathTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteMathTranslator;
};


export type SqliteMathTranslator = SqliteMathTranslator$instance;

export interface SqliteMemberTranslatorProvider$instance extends RelationalMemberTranslatorProvider {
}


export const SqliteMemberTranslatorProvider: {
    new(dependencies: RelationalMemberTranslatorProviderDependencies): SqliteMemberTranslatorProvider;
};


export type SqliteMemberTranslatorProvider = SqliteMemberTranslatorProvider$instance;

export interface SqliteMethodCallTranslatorProvider$instance extends RelationalMethodCallTranslatorProvider {
}


export const SqliteMethodCallTranslatorProvider: {
    new(dependencies: RelationalMethodCallTranslatorProviderDependencies): SqliteMethodCallTranslatorProvider;
};


export type SqliteMethodCallTranslatorProvider = SqliteMethodCallTranslatorProvider$instance;

export interface SqliteObjectToStringTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteObjectToStringTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteObjectToStringTranslator;
};


export type SqliteObjectToStringTranslator = SqliteObjectToStringTranslator$instance;

export interface SqliteParameterBasedSqlProcessor$instance extends RelationalParameterBasedSqlProcessor {
}


export const SqliteParameterBasedSqlProcessor: {
    new(dependencies: RelationalParameterBasedSqlProcessorDependencies, parameters: RelationalParameterBasedSqlProcessorParameters): SqliteParameterBasedSqlProcessor;
};


export type SqliteParameterBasedSqlProcessor = SqliteParameterBasedSqlProcessor$instance;

export interface SqliteParameterBasedSqlProcessorFactory$instance {
    create(parameters: RelationalParameterBasedSqlProcessorParameters): RelationalParameterBasedSqlProcessor;
}


export const SqliteParameterBasedSqlProcessorFactory: {
    new(dependencies: RelationalParameterBasedSqlProcessorDependencies): SqliteParameterBasedSqlProcessorFactory;
};


export type SqliteParameterBasedSqlProcessorFactory = SqliteParameterBasedSqlProcessorFactory$instance;

export interface SqliteQueryableAggregateMethodTranslator$instance {
    translate(method: MethodInfo, source: EnumerableExpression, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteQueryableAggregateMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteQueryableAggregateMethodTranslator;
};


export type SqliteQueryableAggregateMethodTranslator = SqliteQueryableAggregateMethodTranslator$instance;

export interface SqliteQueryableMethodTranslatingExpressionVisitor$instance extends RelationalQueryableMethodTranslatingExpressionVisitor {
}


export const SqliteQueryableMethodTranslatingExpressionVisitor: {
    new(dependencies: QueryableMethodTranslatingExpressionVisitorDependencies, relationalDependencies: RelationalQueryableMethodTranslatingExpressionVisitorDependencies, queryCompilationContext: RelationalQueryCompilationContext): SqliteQueryableMethodTranslatingExpressionVisitor;
    readonly jsonEachKeyColumnName: string;
    readonly jsonEachValueColumnName: string;
    applyJsonSqlConversion(expression: SqlExpression, sqlExpressionFactory: SqliteSqlExpressionFactory, typeMapping: RelationalTypeMapping, isNullable: boolean): SqlExpression;
};


export type SqliteQueryableMethodTranslatingExpressionVisitor = SqliteQueryableMethodTranslatingExpressionVisitor$instance;

export interface SqliteQueryableMethodTranslatingExpressionVisitorFactory$instance {
    create(queryCompilationContext: QueryCompilationContext): QueryableMethodTranslatingExpressionVisitor;
}


export const SqliteQueryableMethodTranslatingExpressionVisitorFactory: {
    new(dependencies: QueryableMethodTranslatingExpressionVisitorDependencies, relationalDependencies: RelationalQueryableMethodTranslatingExpressionVisitorDependencies): SqliteQueryableMethodTranslatingExpressionVisitorFactory;
};


export type SqliteQueryableMethodTranslatingExpressionVisitorFactory = SqliteQueryableMethodTranslatingExpressionVisitorFactory$instance;

export interface SqliteQueryCompilationContext$instance extends RelationalQueryCompilationContext {
    readonly supportsPrecompiledQuery: boolean;
}


export const SqliteQueryCompilationContext: {
    new(dependencies: QueryCompilationContextDependencies, relationalDependencies: RelationalQueryCompilationContextDependencies, async: boolean): SqliteQueryCompilationContext;
    new(dependencies: QueryCompilationContextDependencies, relationalDependencies: RelationalQueryCompilationContextDependencies, async: boolean, precompiling: boolean): SqliteQueryCompilationContext;
};


export type SqliteQueryCompilationContext = SqliteQueryCompilationContext$instance;

export interface SqliteQueryCompilationContextFactory$instance {
    create(async: boolean): QueryCompilationContext;
    createPrecompiled(async: boolean): QueryCompilationContext;
}


export const SqliteQueryCompilationContextFactory: {
    new(dependencies: QueryCompilationContextDependencies, relationalDependencies: RelationalQueryCompilationContextDependencies): SqliteQueryCompilationContextFactory;
};


export type SqliteQueryCompilationContextFactory = SqliteQueryCompilationContextFactory$instance;

export interface SqliteQuerySqlGenerator$instance extends QuerySqlGenerator {
}


export const SqliteQuerySqlGenerator: {
    new(dependencies: QuerySqlGeneratorDependencies): SqliteQuerySqlGenerator;
};


export type SqliteQuerySqlGenerator = SqliteQuerySqlGenerator$instance;

export interface SqliteQuerySqlGeneratorFactory$instance {
    create(): QuerySqlGenerator;
}


export const SqliteQuerySqlGeneratorFactory: {
    new(dependencies: QuerySqlGeneratorDependencies): SqliteQuerySqlGeneratorFactory;
};


export type SqliteQuerySqlGeneratorFactory = SqliteQuerySqlGeneratorFactory$instance;

export interface SqliteQueryStringFactory$instance {
    create(command: DbCommand): string;
}


export const SqliteQueryStringFactory: {
    new(typeMapper: IRelationalTypeMappingSource): SqliteQueryStringFactory;
};


export type SqliteQueryStringFactory = SqliteQueryStringFactory$instance;

export interface SqliteQueryTranslationPostprocessor$instance extends RelationalQueryTranslationPostprocessor {
    process(query: Expression): Expression;
}


export const SqliteQueryTranslationPostprocessor: {
    new(dependencies: QueryTranslationPostprocessorDependencies, relationalDependencies: RelationalQueryTranslationPostprocessorDependencies, queryCompilationContext: RelationalQueryCompilationContext): SqliteQueryTranslationPostprocessor;
};


export type SqliteQueryTranslationPostprocessor = SqliteQueryTranslationPostprocessor$instance;

export interface SqliteQueryTranslationPostprocessorFactory$instance {
    create(queryCompilationContext: QueryCompilationContext): QueryTranslationPostprocessor;
}


export const SqliteQueryTranslationPostprocessorFactory: {
    new(dependencies: QueryTranslationPostprocessorDependencies, relationalDependencies: RelationalQueryTranslationPostprocessorDependencies): SqliteQueryTranslationPostprocessorFactory;
};


export type SqliteQueryTranslationPostprocessorFactory = SqliteQueryTranslationPostprocessorFactory$instance;

export interface SqliteRandomTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteRandomTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteRandomTranslator;
};


export type SqliteRandomTranslator = SqliteRandomTranslator$instance;

export interface SqliteRegexMethodTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteRegexMethodTranslator: {
    new(sqlExpressionFactory: SqliteSqlExpressionFactory): SqliteRegexMethodTranslator;
};


export type SqliteRegexMethodTranslator = SqliteRegexMethodTranslator$instance;

export interface SqliteSqlExpressionFactory$instance extends SqlExpressionFactory {
    applyTypeMapping(sqlExpression: SqlExpression, typeMapping: RelationalTypeMapping): SqlExpression | undefined;
    date(returnType: Type, timestring: SqlExpression, modifiers?: IEnumerable<SqlExpression>, typeMapping?: RelationalTypeMapping): SqlExpression;
    glob(match: SqlExpression, pattern: SqlExpression): GlobExpression;
    regexp(match: SqlExpression, pattern: SqlExpression): RegexpExpression;
    strftime(returnType: Type, format: string, timestring: SqlExpression, modifiers?: IEnumerable<SqlExpression>, typeMapping?: RelationalTypeMapping): SqlExpression;
}


export const SqliteSqlExpressionFactory: {
    new(dependencies: SqlExpressionFactoryDependencies): SqliteSqlExpressionFactory;
};


export type SqliteSqlExpressionFactory = SqliteSqlExpressionFactory$instance;

export interface SqliteSqlNullabilityProcessor$instance extends SqlNullabilityProcessor {
}


export const SqliteSqlNullabilityProcessor: {
    new(dependencies: RelationalParameterBasedSqlProcessorDependencies, parameters: RelationalParameterBasedSqlProcessorParameters): SqliteSqlNullabilityProcessor;
};


export type SqliteSqlNullabilityProcessor = SqliteSqlNullabilityProcessor$instance;

export interface SqliteSqlTranslatingExpressionVisitor$instance extends RelationalSqlTranslatingExpressionVisitor {
    generateGreatest(expressions: IReadOnlyList<SqlExpression>, resultType: Type): SqlExpression;
    generateLeast(expressions: IReadOnlyList<SqlExpression>, resultType: Type): SqlExpression;
}


export const SqliteSqlTranslatingExpressionVisitor: {
    new(dependencies: RelationalSqlTranslatingExpressionVisitorDependencies, queryCompilationContext: QueryCompilationContext, queryableMethodTranslatingExpressionVisitor: QueryableMethodTranslatingExpressionVisitor): SqliteSqlTranslatingExpressionVisitor;
    constructLikePatternParameter(queryContext: QueryContext, baseParameterName: string, startsWith: boolean): string | undefined;
};


export type SqliteSqlTranslatingExpressionVisitor = SqliteSqlTranslatingExpressionVisitor$instance;

export interface SqliteSqlTranslatingExpressionVisitorFactory$instance {
    create(queryCompilationContext: QueryCompilationContext, queryableMethodTranslatingExpressionVisitor: QueryableMethodTranslatingExpressionVisitor): RelationalSqlTranslatingExpressionVisitor;
}


export const SqliteSqlTranslatingExpressionVisitorFactory: {
    new(dependencies: RelationalSqlTranslatingExpressionVisitorDependencies): SqliteSqlTranslatingExpressionVisitorFactory;
};


export type SqliteSqlTranslatingExpressionVisitorFactory = SqliteSqlTranslatingExpressionVisitorFactory$instance;

export interface SqliteStringAggregateMethodTranslator$instance {
    translate(method: MethodInfo, source: EnumerableExpression, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteStringAggregateMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteStringAggregateMethodTranslator;
};


export type SqliteStringAggregateMethodTranslator = SqliteStringAggregateMethodTranslator$instance;

export interface SqliteStringLengthTranslator$instance {
    translate(instance: SqlExpression, member: MemberInfo, returnType: Type, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteStringLengthTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteStringLengthTranslator;
};


export type SqliteStringLengthTranslator = SqliteStringLengthTranslator$instance;

export interface SqliteStringMethodTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteStringMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteStringMethodTranslator;
};


export type SqliteStringMethodTranslator = SqliteStringMethodTranslator$instance;

export interface SqliteSubstrMethodTranslator$instance {
    translate(instance: SqlExpression, method: MethodInfo, arguments: IReadOnlyList<SqlExpression>, logger: IDiagnosticsLogger<DbLoggerCategory$Query>): SqlExpression | undefined;
}


export const SqliteSubstrMethodTranslator: {
    new(sqlExpressionFactory: ISqlExpressionFactory): SqliteSubstrMethodTranslator;
};


export type SqliteSubstrMethodTranslator = SqliteSubstrMethodTranslator$instance;

export interface SqliteTypeMappingPostprocessor$instance extends RelationalTypeMappingPostprocessor {
}


export const SqliteTypeMappingPostprocessor: {
    new(dependencies: QueryTranslationPostprocessorDependencies, relationalDependencies: RelationalQueryTranslationPostprocessorDependencies, queryCompilationContext: RelationalQueryCompilationContext): SqliteTypeMappingPostprocessor;
};


export type SqliteTypeMappingPostprocessor = SqliteTypeMappingPostprocessor$instance;

