// Generated by tsbindgen - Architecture
// Namespace: System.Collections.Generic
// Assembly: Microsoft.Extensions.DependencyModel, System.Collections, System.Private.CoreLib

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { RuntimeAssetGroup, RuntimeFile } from "../../Microsoft.Extensions.DependencyModel/internal/index.js";
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";

export abstract class CollectionExtensions$instance {
    static getDefaultAssets(self: IEnumerable<RuntimeAssetGroup>): IEnumerable<System_Internal.String>;
    static getDefaultGroup(self: IEnumerable<RuntimeAssetGroup>): RuntimeAssetGroup | undefined;
    static getDefaultRuntimeFileAssets(self: IEnumerable<RuntimeAssetGroup>): IEnumerable<RuntimeFile>;
    static getRuntimeAssets(self: IEnumerable<RuntimeAssetGroup>, runtime: string): IEnumerable<System_Internal.String>;
    static getRuntimeFileAssets(self: IEnumerable<RuntimeAssetGroup>, runtime: string): IEnumerable<RuntimeFile>;
    static getRuntimeGroup(self: IEnumerable<RuntimeAssetGroup>, runtime: string): RuntimeAssetGroup | undefined;
}


export type CollectionExtensions = CollectionExtensions$instance;

