// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Extensions.DependencyModel
// Assembly: Microsoft.Extensions.DependencyModel

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { ICompilationAssemblyResolver } from "../../Microsoft.Extensions.DependencyModel.Resolution/internal/index.js";
import type { IEnumerable_1, IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import type { Stream } from "@tsonic/dotnet/System.IO/internal/index.js";
import type { Assembly, AssemblyName } from "@tsonic/dotnet/System.Reflection/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, IDisposable, IEquatable_1, Int32, Nullable_1, Object as ClrObject, String as ClrString, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface IDependencyContextReader$instance extends IDisposable {
    readonly __tsonic_iface_Microsoft_Extensions_DependencyModel_IDependencyContextReader: never;

    Read(stream: Stream): DependencyContext;
}


export interface IDependencyContextReader$instance extends System_Internal.IDisposable {}

export type IDependencyContextReader = IDependencyContextReader$instance;

export interface Dependency$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_Dependency: never;

    readonly __tsonic_iface_System_IEquatable_1: never;

    readonly Name: string;
    readonly Version: string;
    Equals(other: Dependency): boolean;
    Equals(obj: JsValue | null): boolean;
    GetHashCode(): int;
}


export const Dependency: {
    new(name: string, version: string): Dependency;
};


export type Dependency = Dependency$instance;

export interface CompilationLibrary$instance extends Library {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_CompilationLibrary: never;

    readonly Assemblies: IReadOnlyList_1<System_Internal.String>;
    ResolveReferencePaths(): IEnumerable_1<System_Internal.String>;
    ResolveReferencePaths(...customResolvers: ICompilationAssemblyResolver[]): IEnumerable_1<System_Internal.String>;
}


export const CompilationLibrary: {
    new(type: string, name: string, version: string, hash: string | null, assemblies: IEnumerable_1<System_Internal.String>, dependencies: IEnumerable_1<Dependency>, serviceable: boolean): CompilationLibrary;
    new(type: string, name: string, version: string, hash: string | null, assemblies: IEnumerable_1<System_Internal.String>, dependencies: IEnumerable_1<Dependency>, serviceable: boolean, path: string | null, hashPath: string | null): CompilationLibrary;
};


export type CompilationLibrary = CompilationLibrary$instance;

export interface CompilationOptions$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_CompilationOptions: never;

    readonly AllowUnsafe: Nullable_1<System_Internal.Boolean>;
    readonly DebugType: string | null;
    readonly Defines: IReadOnlyList_1<string | null>;
    readonly DelaySign: Nullable_1<System_Internal.Boolean>;
    readonly EmitEntryPoint: Nullable_1<System_Internal.Boolean>;
    readonly GenerateXmlDocumentation: Nullable_1<System_Internal.Boolean>;
    readonly KeyFile: string | null;
    readonly LanguageVersion: string | null;
    readonly Optimize: Nullable_1<System_Internal.Boolean>;
    readonly Platform: string | null;
    readonly PublicSign: Nullable_1<System_Internal.Boolean>;
    readonly WarningsAsErrors: Nullable_1<System_Internal.Boolean>;
}


export const CompilationOptions: {
    new(defines: IEnumerable_1<string | null>, languageVersion: string | null, platform: string | null, allowUnsafe: Nullable_1<System_Internal.Boolean>, warningsAsErrors: Nullable_1<System_Internal.Boolean>, optimize: Nullable_1<System_Internal.Boolean>, keyFile: string | null, delaySign: Nullable_1<System_Internal.Boolean>, publicSign: Nullable_1<System_Internal.Boolean>, debugType: string | null, emitEntryPoint: Nullable_1<System_Internal.Boolean>, generateXmlDocumentation: Nullable_1<System_Internal.Boolean>): CompilationOptions;
    readonly Default: CompilationOptions;
};


export type CompilationOptions = CompilationOptions$instance;

export interface DependencyContext$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_DependencyContext: never;

    readonly CompilationOptions: CompilationOptions;
    readonly CompileLibraries: IReadOnlyList_1<CompilationLibrary>;
    readonly RuntimeGraph: IReadOnlyList_1<RuntimeFallbacks>;
    readonly RuntimeLibraries: IReadOnlyList_1<RuntimeLibrary>;
    readonly Target: TargetInfo;
    Merge(other: DependencyContext): DependencyContext;
}


export const DependencyContext: {
    new(target: TargetInfo, compilationOptions: CompilationOptions, compileLibraries: IEnumerable_1<CompilationLibrary>, runtimeLibraries: IEnumerable_1<RuntimeLibrary>, runtimeGraph: IEnumerable_1<RuntimeFallbacks>): DependencyContext;
    readonly Default: DependencyContext | null;
    Load(assembly: Assembly): DependencyContext | null;
};


export type DependencyContext = DependencyContext$instance;

export interface DependencyContextJsonReader$instance extends IDependencyContextReader$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_DependencyContextJsonReader: never;

    readonly __tsonic_iface_Microsoft_Extensions_DependencyModel_IDependencyContextReader: never;
    readonly __tsonic_iface_System_IDisposable: never;

    Dispose(disposing: boolean): void;
    Dispose(): void;
    Read(stream: Stream): DependencyContext;
}


export const DependencyContextJsonReader: {
    new(): DependencyContextJsonReader;
};


export interface __DependencyContextJsonReader$views {
    As_IDependencyContextReader(): IDependencyContextReader$instance;
}

export type DependencyContextJsonReader = DependencyContextJsonReader$instance & __DependencyContextJsonReader$views;


export interface DependencyContextLoader$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_DependencyContextLoader: never;

    Load(assembly: Assembly): DependencyContext | null;
}


export const DependencyContextLoader: {
    new(): DependencyContextLoader;
    readonly Default: DependencyContextLoader;
};


export type DependencyContextLoader = DependencyContextLoader$instance;

export interface DependencyContextWriter$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_DependencyContextWriter: never;

    Write(context: DependencyContext, stream: Stream): void;
}


export const DependencyContextWriter: {
    new(): DependencyContextWriter;
};


export type DependencyContextWriter = DependencyContextWriter$instance;

export interface Library$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_Library: never;

    readonly Dependencies: IReadOnlyList_1<Dependency>;
    readonly Hash: string | null;
    readonly HashPath: string | null;
    readonly Name: string;
    readonly Path: string | null;
    readonly RuntimeStoreManifestName: string | null;
    readonly Serviceable: boolean;
    readonly Type: string;
    readonly Version: string;
}


export const Library: {
    new(type: string, name: string, version: string, hash: string | null, dependencies: IEnumerable_1<Dependency>, serviceable: boolean): Library;
    new(type: string, name: string, version: string, hash: string | null, dependencies: IEnumerable_1<Dependency>, serviceable: boolean, path: string | null, hashPath: string | null): Library;
    new(type: string, name: string, version: string, hash: string | null, dependencies: IEnumerable_1<Dependency>, serviceable: boolean, path: string | null, hashPath: string | null, runtimeStoreManifestName: string | null): Library;
};


export type Library = Library$instance;

export interface ResourceAssembly$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_ResourceAssembly: never;

    Locale: string;
    readonly LocalPath: string | null;
    Path: string;
}


export const ResourceAssembly: {
    new(path: string, locale: string): ResourceAssembly;
    new(path: string, locale: string, localPath: string | null): ResourceAssembly;
};


export type ResourceAssembly = ResourceAssembly$instance;

export interface RuntimeAssembly$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_RuntimeAssembly: never;

    readonly Name: AssemblyName;
    readonly Path: string;
}


export const RuntimeAssembly: {
    new(assemblyName: string, path: string): RuntimeAssembly;
    Create(path: string): RuntimeAssembly;
};


export type RuntimeAssembly = RuntimeAssembly$instance;

export interface RuntimeAssetGroup$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_RuntimeAssetGroup: never;

    readonly AssetPaths: IReadOnlyList_1<System_Internal.String>;
    readonly Runtime: string | null;
    readonly RuntimeFiles: IReadOnlyList_1<RuntimeFile>;
}


export const RuntimeAssetGroup: {
    new(runtime: string | null, assetPaths: string[]): RuntimeAssetGroup;
    new(runtime: string | null, assetPaths: IEnumerable_1<System_Internal.String>): RuntimeAssetGroup;
    new(runtime: string | null, runtimeFiles: IEnumerable_1<RuntimeFile>): RuntimeAssetGroup;
};


export type RuntimeAssetGroup = RuntimeAssetGroup$instance;

export interface RuntimeFallbacks$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_RuntimeFallbacks: never;

    Fallbacks: IReadOnlyList_1<string | null>;
    Runtime: string;
}


export const RuntimeFallbacks: {
    new(runtime: string, fallbacks: (string | null)[]): RuntimeFallbacks;
    new(runtime: string, fallbacks: IEnumerable_1<string | null>): RuntimeFallbacks;
};


export type RuntimeFallbacks = RuntimeFallbacks$instance;

export interface RuntimeFile$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_RuntimeFile: never;

    readonly AssemblyVersion: string | null;
    readonly FileVersion: string | null;
    readonly LocalPath: string | null;
    readonly Path: string;
}


export const RuntimeFile: {
    new(path: string, assemblyVersion: string | null, fileVersion: string | null): RuntimeFile;
    new(path: string, assemblyVersion: string | null, fileVersion: string | null, localPath: string | null): RuntimeFile;
};


export type RuntimeFile = RuntimeFile$instance;

export interface RuntimeLibrary$instance extends Library {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_RuntimeLibrary: never;

    readonly NativeLibraryGroups: IReadOnlyList_1<RuntimeAssetGroup>;
    readonly ResourceAssemblies: IReadOnlyList_1<ResourceAssembly>;
    readonly RuntimeAssemblyGroups: IReadOnlyList_1<RuntimeAssetGroup>;
}


export const RuntimeLibrary: {
    new(type: string, name: string, version: string, hash: string | null, runtimeAssemblyGroups: IReadOnlyList_1<RuntimeAssetGroup>, nativeLibraryGroups: IReadOnlyList_1<RuntimeAssetGroup>, resourceAssemblies: IEnumerable_1<ResourceAssembly>, dependencies: IEnumerable_1<Dependency>, serviceable: boolean): RuntimeLibrary;
    new(type: string, name: string, version: string, hash: string | null, runtimeAssemblyGroups: IReadOnlyList_1<RuntimeAssetGroup>, nativeLibraryGroups: IReadOnlyList_1<RuntimeAssetGroup>, resourceAssemblies: IEnumerable_1<ResourceAssembly>, dependencies: IEnumerable_1<Dependency>, serviceable: boolean, path: string | null, hashPath: string | null): RuntimeLibrary;
    new(type: string, name: string, version: string, hash: string | null, runtimeAssemblyGroups: IReadOnlyList_1<RuntimeAssetGroup>, nativeLibraryGroups: IReadOnlyList_1<RuntimeAssetGroup>, resourceAssemblies: IEnumerable_1<ResourceAssembly>, dependencies: IEnumerable_1<Dependency>, serviceable: boolean, path: string | null, hashPath: string | null, runtimeStoreManifestName: string | null): RuntimeLibrary;
};


export type RuntimeLibrary = RuntimeLibrary$instance;

export interface TargetInfo$instance {
    readonly __tsonic_type_Microsoft_Extensions_DependencyModel_TargetInfo: never;

    readonly Framework: string;
    readonly IsPortable: boolean;
    readonly Runtime: string | null;
    readonly RuntimeSignature: string | null;
}


export const TargetInfo: {
    new(framework: string, runtime: string | null, runtimeSignature: string | null, isPortable: boolean): TargetInfo;
};


export type TargetInfo = TargetInfo$instance;

export abstract class DependencyContextExtensions$instance {
    static GetDefaultAssemblyNames(self: DependencyContext): IEnumerable_1<AssemblyName>;
    static GetDefaultAssemblyNames(self: RuntimeLibrary, context: DependencyContext): IEnumerable_1<AssemblyName>;
    static GetDefaultNativeAssets(self: DependencyContext): IEnumerable_1<System_Internal.String>;
    static GetDefaultNativeAssets(self: RuntimeLibrary, context: DependencyContext): IEnumerable_1<System_Internal.String>;
    static GetDefaultNativeRuntimeFileAssets(self: DependencyContext): IEnumerable_1<RuntimeFile>;
    static GetDefaultNativeRuntimeFileAssets(self: RuntimeLibrary, context: DependencyContext): IEnumerable_1<RuntimeFile>;
    static GetRuntimeAssemblyNames(self: DependencyContext, runtimeIdentifier: string): IEnumerable_1<AssemblyName>;
    static GetRuntimeAssemblyNames(self: RuntimeLibrary, context: DependencyContext, runtimeIdentifier: string): IEnumerable_1<AssemblyName>;
    static GetRuntimeNativeAssets(self: DependencyContext, runtimeIdentifier: string): IEnumerable_1<System_Internal.String>;
    static GetRuntimeNativeAssets(self: RuntimeLibrary, context: DependencyContext, runtimeIdentifier: string): IEnumerable_1<System_Internal.String>;
    static GetRuntimeNativeRuntimeFileAssets(self: DependencyContext, runtimeIdentifier: string): IEnumerable_1<RuntimeFile>;
    static GetRuntimeNativeRuntimeFileAssets(self: RuntimeLibrary, context: DependencyContext, runtimeIdentifier: string): IEnumerable_1<RuntimeFile>;
}


export type DependencyContextExtensions = DependencyContextExtensions$instance;

