// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Metadata.Conventions
// Assembly: Microsoft.EntityFrameworkCore, Microsoft.EntityFrameworkCore.Relational, Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Dictionary } from "@tsonic/dotnet/System.Collections.Generic.js";
import type { Boolean as ClrBoolean, Nullable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { ModelBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import type { IConventionPropertyBuilder } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Builders.js";
import * as Microsoft_EntityFrameworkCore_Metadata_Conventions_Infrastructure_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure.js";
import type { IProviderConventionSetBuilder, ProviderConventionSetBuilderDependencies, RelationalConventionSetBuilder, RelationalConventionSetBuilderDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure.js";
import * as Microsoft_EntityFrameworkCore_Metadata_Conventions_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Conventions.js";
import type { ConventionSet, IConvention, IConventionContext, IEntityTypeAnnotationChangedConvention, IEntityTypeBaseTypeChangedConvention, IEntityTypePrimaryKeyChangedConvention, IForeignKeyAddedConvention, IForeignKeyOwnershipChangedConvention, IForeignKeyPropertiesChangedConvention, IForeignKeyRemovedConvention, IModelFinalizedConvention, IModelFinalizingConvention, IPropertyAnnotationChangedConvention, RelationalRuntimeModelConvention, RelationalValueGenerationConvention, SharedTableConvention, StoreGenerationConvention } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.Conventions.js";
import type { IConventionAnnotation, IConventionProperty, IProperty, RuntimeProperty, StoreObjectIdentifier, ValueGenerated } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";

export interface SqliteConventionSetBuilder$instance extends RelationalConventionSetBuilder {
    CreateConventionSet(): ConventionSet;
}


export const SqliteConventionSetBuilder: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies): SqliteConventionSetBuilder;
    Build(): ConventionSet;
    CreateModelBuilder(): ModelBuilder;
};


export type SqliteConventionSetBuilder = SqliteConventionSetBuilder$instance;

export abstract class SqliteRuntimeModelConvention$protected {
    protected ProcessPropertyAnnotations(annotations: Dictionary<System_Internal.String, unknown>, property: IProperty, runtimeProperty: RuntimeProperty, runtime: boolean): void;
}


export interface SqliteRuntimeModelConvention$instance extends SqliteRuntimeModelConvention$protected, RelationalRuntimeModelConvention {
}


export const SqliteRuntimeModelConvention: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies): SqliteRuntimeModelConvention;
};


export type SqliteRuntimeModelConvention = SqliteRuntimeModelConvention$instance;

export abstract class SqliteSharedTableConvention$protected {
    protected readonly CheckConstraintsUniqueAcrossTables: boolean;
}


export interface SqliteSharedTableConvention$instance extends SqliteSharedTableConvention$protected, SharedTableConvention {
}


export const SqliteSharedTableConvention: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies): SqliteSharedTableConvention;
};


export type SqliteSharedTableConvention = SqliteSharedTableConvention$instance;

export abstract class SqliteStoreGenerationConvention$protected {
    protected Validate(property: IConventionProperty, storeObject: StoreObjectIdentifier): void;
}


export interface SqliteStoreGenerationConvention$instance extends SqliteStoreGenerationConvention$protected, StoreGenerationConvention {
    ProcessPropertyAnnotationChanged(propertyBuilder: IConventionPropertyBuilder, name: string, annotation: IConventionAnnotation, oldAnnotation: IConventionAnnotation, context: IConventionContext<IConventionAnnotation>): void;
}


export const SqliteStoreGenerationConvention: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies): SqliteStoreGenerationConvention;
};


export type SqliteStoreGenerationConvention = SqliteStoreGenerationConvention$instance;

export abstract class SqliteValueGenerationConvention$protected {
    protected GetValueGenerated(property: IConventionProperty): Nullable<ValueGenerated>;
}


export interface SqliteValueGenerationConvention$instance extends SqliteValueGenerationConvention$protected, RelationalValueGenerationConvention {
    ProcessPropertyAnnotationChanged(propertyBuilder: IConventionPropertyBuilder, name: string, annotation: IConventionAnnotation, oldAnnotation: IConventionAnnotation, context: IConventionContext<IConventionAnnotation>): void;
}


export const SqliteValueGenerationConvention: {
    new(dependencies: ProviderConventionSetBuilderDependencies, relationalDependencies: RelationalConventionSetBuilderDependencies): SqliteValueGenerationConvention;
};


export type SqliteValueGenerationConvention = SqliteValueGenerationConvention$instance;

