// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { SqliteValueGenerationStrategy } from "../../Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Int64, Nullable, Object as ClrObject, String as ClrString, Type, Void } from "@tsonic/dotnet/System.js";
import type { EventDefinition, IDiagnosticsLogger } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";
import type { DbLoggerCategory$Infrastructure, DbLoggerCategory$Migrations, DbLoggerCategory$Model$Validation, DbLoggerCategory$Scaffolding } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.js";
import type { IEntityType, IKey, IReadOnlyProperty, IReadOnlySequence } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";

export abstract class SqliteLoggerExtensions$instance {
    static columnFound(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, tableName: string, columnName: string, dataTypeName: string, notNull: boolean, defaultValue: string): void;
    static compositeKeyWithValueGeneration(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Model$Validation>, key: IKey): void;
    static conflictingValueGenerationStrategiesWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Model$Validation>, sqliteValueGenerationStrategy: SqliteValueGenerationStrategy, otherValueGenerationStrategy: string, property: IReadOnlyProperty): void;
    static foreignKeyFound(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, tableName: string, id: long, principalTableName: string, deleteAction: string): void;
    static foreignKeyPrincipalColumnMissingWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, foreignKeyName: string, tableName: string, principalColumnName: string, principalTableName: string): void;
    static foreignKeyReferencesMissingTableWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, id: string, tableName: string, principalTableName: string): void;
    static formatWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, columnName: string, tableName: string, type: string): void;
    static indexFound(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, indexName: string, tableName: string, unique: Nullable<System_Internal.Boolean>): void;
    static inferringTypes(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, tableName: string): void;
    static missingTableWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, tableName: string): void;
    static outOfRangeWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, columnName: string, tableName: string, type: string): void;
    static primaryKeyFound(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, primaryKeyName: string, tableName: string): void;
    static schemaConfiguredWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Model$Validation>, entityType: IEntityType, schema: string): void;
    static schemasNotSupportedWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>): void;
    static sequenceConfiguredWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Model$Validation>, sequence: IReadOnlySequence): void;
    static tableFound(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, tableName: string): void;
    static tableRebuildPendingWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Migrations>, operationType: Type, tableName: string): void;
    static unexpectedConnectionTypeWarning(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Infrastructure>, connectionType: Type): void;
    static uniqueConstraintFound(diagnostics: IDiagnosticsLogger<DbLoggerCategory$Scaffolding>, uniqueConstraintName: string, tableName: string): void;
}


export type SqliteLoggerExtensions = SqliteLoggerExtensions$instance;

export abstract class SqliteResources$instance {
    static logCompositeKeyWithValueGeneration(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined>;
    static logConflictingValueGenerationStrategies(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String, System_Internal.String, System_Internal.String>;
    static logForeignKeyScaffoldErrorPrincipalTableNotFound(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined, string | undefined>;
    static logFormatWarning(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined, string | undefined>;
    static logFoundColumn(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined, string | undefined, System_Internal.Boolean, string | undefined>;
    static logFoundForeignKey(logger: IDiagnosticsLogger): EventDefinition<string | undefined, System_Internal.Int64, string | undefined, string | undefined>;
    static logFoundIndex(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined, Nullable<System_Internal.Boolean>>;
    static logFoundPrimaryKey(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined>;
    static logFoundTable(logger: IDiagnosticsLogger): EventDefinition<string | undefined>;
    static logFoundUniqueConstraint(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined>;
    static logInferringTypes(logger: IDiagnosticsLogger): EventDefinition<string | undefined>;
    static logMissingTable(logger: IDiagnosticsLogger): EventDefinition<string | undefined>;
    static logOutOfRangeWarning(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined, string | undefined>;
    static logPrincipalColumnNotFound(logger: IDiagnosticsLogger): EventDefinition<string | undefined, string | undefined, string | undefined, string | undefined>;
    static logSchemaConfigured(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String>;
    static logSequenceConfigured(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String>;
    static logTableRebuildPendingWarning(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String, System_Internal.String>;
    static logUnexpectedConnectionType(logger: IDiagnosticsLogger): EventDefinition<System_Internal.String>;
    static logUsingSchemaSelectionsWarning(logger: IDiagnosticsLogger): EventDefinition;
}


export type SqliteResources = SqliteResources$instance;

export abstract class SqliteStrings$instance {
    static readonly applyNotSupported: string;
    static readonly defaultNotSupported: string;
    static readonly executeUpdateJsonPartialUpdateDoesNotSupportUlong: string;
    static readonly migrationScriptGenerationNotSupported: string;
    static readonly sequencesNotSupported: string;
    static aggregateOperationNotSupported(aggregateOperator: unknown, type: unknown): string;
    static duplicateColumnNameSridMismatch(entityType1: unknown, property1: unknown, entityType2: unknown, property2: unknown, columnName: unknown, table: unknown): string;
    static incompatibleSqlReturningClauseMismatch(table: unknown, entityType: unknown, otherEntityType: unknown, entityTypeWithSqlReturningClause: unknown, entityTypeWithoutSqlReturningClause: unknown): string;
    static invalidMigrationOperation(operation: unknown): string;
    static orderByNotSupported(type: unknown): string;
    static queryingIntoJsonCollectionsNotSupported(sqliteVersion: unknown): string;
    static storedProceduresNotSupported(entityType: unknown): string;
}


export type SqliteStrings = SqliteStrings$instance;

