// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Storage.Json.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Byte, DateTime, DateTimeOffset, Decimal, Guid, Object as ClrObject, Void } from "@tsonic/dotnet/System.js";
import type { Expression } from "@tsonic/dotnet/System.Linq.Expressions.js";
import type { Utf8JsonWriter } from "@tsonic/dotnet/System.Text.Json.js";
import * as Microsoft_EntityFrameworkCore_Storage_Json_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.Json.js";
import type { JsonValueReaderWriter, Utf8JsonReaderManager } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.Json.js";

export interface SqliteJsonByteArrayReaderWriter$instance extends JsonValueReaderWriter<byte[]> {
    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown): byte[];
    ToJsonTyped(writer: Utf8JsonWriter, value: byte[]): void;
}


export const SqliteJsonByteArrayReaderWriter: {
    readonly Instance: SqliteJsonByteArrayReaderWriter;
};


export type SqliteJsonByteArrayReaderWriter = SqliteJsonByteArrayReaderWriter$instance;

export interface SqliteJsonDateTimeOffsetReaderWriter$instance extends JsonValueReaderWriter<DateTimeOffset> {
    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown): DateTimeOffset;
    ToJsonTyped(writer: Utf8JsonWriter, value: DateTimeOffset): void;
}


export const SqliteJsonDateTimeOffsetReaderWriter: {
    readonly Instance: SqliteJsonDateTimeOffsetReaderWriter;
};


export type SqliteJsonDateTimeOffsetReaderWriter = SqliteJsonDateTimeOffsetReaderWriter$instance;

export interface SqliteJsonDateTimeReaderWriter$instance extends JsonValueReaderWriter<DateTime> {
    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown): DateTime;
    ToJsonTyped(writer: Utf8JsonWriter, value: DateTime): void;
}


export const SqliteJsonDateTimeReaderWriter: {
    readonly Instance: SqliteJsonDateTimeReaderWriter;
};


export type SqliteJsonDateTimeReaderWriter = SqliteJsonDateTimeReaderWriter$instance;

export interface SqliteJsonDecimalReaderWriter$instance extends JsonValueReaderWriter<System_Internal.Decimal> {
    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown): decimal;
    ToJsonTyped(writer: Utf8JsonWriter, value: decimal): void;
}


export const SqliteJsonDecimalReaderWriter: {
    readonly Instance: SqliteJsonDecimalReaderWriter;
};


export type SqliteJsonDecimalReaderWriter = SqliteJsonDecimalReaderWriter$instance;

export interface SqliteJsonGuidReaderWriter$instance extends JsonValueReaderWriter<Guid> {
    readonly ConstructorExpression: Expression;
    FromJsonTyped(manager: Utf8JsonReaderManager, existingObject?: unknown): Guid;
    ToJsonTyped(writer: Utf8JsonWriter, value: Guid): void;
}


export const SqliteJsonGuidReaderWriter: {
    readonly Instance: SqliteJsonGuidReaderWriter;
};


export type SqliteJsonGuidReaderWriter = SqliteJsonGuidReaderWriter$instance;

