// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Metadata.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IEnumerable } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString } from "@tsonic/dotnet/System.js";
import type { IAnnotation } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure.js";
import * as Microsoft_EntityFrameworkCore_Metadata_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";
import type { IColumn, IRelationalAnnotationProvider, IRelationalModel, RelationalAnnotationProvider, RelationalAnnotationProviderDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata.js";

export interface SqliteAnnotationProvider$instance extends RelationalAnnotationProvider {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Metadata_IRelationalAnnotationProvider: never;

    For(model: IRelationalModel, designTime: boolean): IEnumerable<IAnnotation>;
    For(column: IColumn, designTime: boolean): IEnumerable<IAnnotation>;
}


export const SqliteAnnotationProvider: {
    new(dependencies: RelationalAnnotationProviderDependencies): SqliteAnnotationProvider;
};


export type SqliteAnnotationProvider = SqliteAnnotationProvider$instance;

export abstract class SqliteAnnotationNames$instance {
    static readonly Prefix: string;
    static readonly LegacyAutoincrement: string;
    static readonly Autoincrement: string;
    static readonly InlinePrimaryKey: string;
    static readonly InlinePrimaryKeyName: string;
    static readonly InitSpatialMetaData: string;
    static readonly Srid: string;
    static readonly UseSqlReturningClause: string;
    static readonly ValueGenerationStrategy: string;
}


export type SqliteAnnotationNames = SqliteAnnotationNames$instance;

