// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Scaffolding.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { DbConnection } from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import type { String as ClrString, Void } from "@tsonic/dotnet/System/internal/index.js";
import type { MethodCallCodeFragment } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Design/internal/index.js";
import type { IDiagnosticsLogger_1 } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import type { DatabaseModel, DatabaseTable } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Scaffolding.Metadata/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Scaffolding_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Scaffolding/internal/index.js";
import type { DatabaseModelFactory, DatabaseModelFactoryOptions, IDatabaseModelFactory, IProviderConfigurationCodeGenerator, ProviderCodeGenerator, ProviderCodeGeneratorDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Scaffolding/internal/index.js";
import type { IRelationalTypeMappingSource } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage/internal/index.js";
import type { DbLoggerCategory$Scaffolding } from "@tsonic/efcore/Microsoft.EntityFrameworkCore/internal/index.js";

export interface SqliteCodeGenerator$instance extends ProviderCodeGenerator {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Sqlite_Scaffolding_Internal_SqliteCodeGenerator: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Scaffolding_IProviderConfigurationCodeGenerator: never;

    GenerateUseProvider(connectionString: string, providerOptions: MethodCallCodeFragment): MethodCallCodeFragment;
}


export const SqliteCodeGenerator: {
    new(dependencies: ProviderCodeGeneratorDependencies): SqliteCodeGenerator;
};


export type SqliteCodeGenerator = SqliteCodeGenerator$instance;

export interface SqliteDatabaseModelFactory$instance extends DatabaseModelFactory {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Sqlite_Scaffolding_Internal_SqliteDatabaseModelFactory: never;

    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Scaffolding_IDatabaseModelFactory: never;

    Create(connectionString: string, options: DatabaseModelFactoryOptions): DatabaseModel;
    Create(connection: DbConnection, options: DatabaseModelFactoryOptions): DatabaseModel;
    InferClrTypes(connection: DbConnection, table: DatabaseTable): void;
}


export const SqliteDatabaseModelFactory: {
    new(logger: IDiagnosticsLogger_1<DbLoggerCategory$Scaffolding>, typeMappingSource: IRelationalTypeMappingSource): SqliteDatabaseModelFactory;
};


export type SqliteDatabaseModelFactory = SqliteDatabaseModelFactory$instance;

