// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Design.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IDictionary_2, IReadOnlyList_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Boolean as ClrBoolean, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Design_Internal_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Design.Internal/internal/index.js";
import type { CSharpRuntimeAnnotationCodeGeneratorDependencies, CSharpRuntimeAnnotationCodeGeneratorParameters, RelationalCSharpRuntimeAnnotationCodeGenerator, RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Design.Internal/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Design_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Design/internal/index.js";
import type { AnnotationCodeGenerator, AnnotationCodeGeneratorDependencies, IAnnotationCodeGenerator, IDesignTimeServices, MethodCallCodeFragment } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Design/internal/index.js";
import type { IAnnotation } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Infrastructure/internal/index.js";
import type { IColumn, IProperty, IRelationalModel } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Metadata/internal/index.js";
import type { IServiceCollection } from "@tsonic/microsoft-extensions/Microsoft.Extensions.DependencyInjection/internal/index.js";

export interface SqliteAnnotationCodeGenerator$instance extends AnnotationCodeGenerator {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_IAnnotationCodeGenerator: never;

    GenerateFluentApiCalls(property: IProperty, annotations: IDictionary_2<System_Internal.String, IAnnotation>): IReadOnlyList_1<MethodCallCodeFragment>;
    IsHandledByConvention(property: IProperty, annotation: IAnnotation): boolean;
}


export const SqliteAnnotationCodeGenerator: {
    new(dependencies: AnnotationCodeGeneratorDependencies): SqliteAnnotationCodeGenerator;
};


export type SqliteAnnotationCodeGenerator = SqliteAnnotationCodeGenerator$instance;

export interface SqliteCSharpRuntimeAnnotationCodeGenerator$instance extends RelationalCSharpRuntimeAnnotationCodeGenerator {
    Generate(model: IRelationalModel, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(property: IProperty, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
    Generate(column: IColumn, parameters: CSharpRuntimeAnnotationCodeGeneratorParameters): void;
}


export const SqliteCSharpRuntimeAnnotationCodeGenerator: {
    new(dependencies: CSharpRuntimeAnnotationCodeGeneratorDependencies, relationalDependencies: RelationalCSharpRuntimeAnnotationCodeGeneratorDependencies): SqliteCSharpRuntimeAnnotationCodeGenerator;
};


export type SqliteCSharpRuntimeAnnotationCodeGenerator = SqliteCSharpRuntimeAnnotationCodeGenerator$instance;

export interface SqliteDesignTimeServices$instance {
    readonly __tsonic_iface_Microsoft_EntityFrameworkCore_Design_IDesignTimeServices: never;

    ConfigureDesignTimeServices(serviceCollection: IServiceCollection): void;
}


export const SqliteDesignTimeServices: {
    new(): SqliteDesignTimeServices;
};


export type SqliteDesignTimeServices = SqliteDesignTimeServices$instance;

