// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Migrations.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Boolean as ClrBoolean, IAsyncDisposable, IDisposable, Object as ClrObject, String as ClrString, Void } from "@tsonic/dotnet/System.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task, ValueTask } from "@tsonic/dotnet/System.Threading.Tasks.js";
import * as Microsoft_EntityFrameworkCore_Migrations_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.js";
import type { HistoryRepository, HistoryRepositoryDependencies, IHistoryRepository, IMigrationsDatabaseLock, LockReleaseBehavior } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Migrations.js";
import type { IRelationalCommand, RelationalCommandParameterObject } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Storage.js";

export interface SqliteHistoryRepository$instance extends HistoryRepository {
    readonly ExistsSql: string;
    readonly LockReleaseBehavior: LockReleaseBehavior;
    readonly LockTableName: string;
    AcquireDatabaseLock(): IMigrationsDatabaseLock;
    AcquireDatabaseLockAsync(cancellationToken?: CancellationToken): Task<IMigrationsDatabaseLock>;
    GetBeginIfExistsScript(migrationId: string): string;
    GetBeginIfNotExistsScript(migrationId: string): string;
    GetCreateIfNotExistsScript(): string;
    GetEndIfScript(): string;
    InterpretExistsResult(value: unknown): boolean;
}


export const SqliteHistoryRepository: {
    new(dependencies: HistoryRepositoryDependencies): SqliteHistoryRepository;
};


export type SqliteHistoryRepository = SqliteHistoryRepository$instance;

export interface SqliteMigrationDatabaseLock$instance {
    readonly HistoryRepository: IHistoryRepository;
    Dispose(): void;
    DisposeAsync(): ValueTask;
}


export const SqliteMigrationDatabaseLock: {
    new(releaseLockCommand: IRelationalCommand, relationalCommandParameters: RelationalCommandParameterObject, historyRepository: IHistoryRepository, cancellationToken: CancellationToken): SqliteMigrationDatabaseLock;
};


export type SqliteMigrationDatabaseLock = SqliteMigrationDatabaseLock$instance;

