// Generated by tsbindgen - Architecture
// Namespace: Microsoft.DotNet.PlatformAbstractions
// Assembly: Microsoft.Extensions.DependencyModel

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import type { IEqualityComparer_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Int32, Object as ClrObject, String as ClrString, ValueType, Void } from "@tsonic/dotnet/System/internal/index.js";

export interface HashCodeCombiner$instance {
    readonly CombinedHash: int;
    Add(i: int): void;
    Add(s: string): void;
    Add(o: unknown): void;
    Add<TValue>(value: TValue, comparer: IEqualityComparer_1<TValue>): void;
}


export const HashCodeCombiner: {
    new(): HashCodeCombiner;
    Start(): HashCodeCombiner;
};


export type HashCodeCombiner = HashCodeCombiner$instance;

