// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Data.Sqlite
// Assembly: Microsoft.Data.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { sqlite3, sqlite3_stmt } from "../../SQLitePCL/internal/index.js";
import type { IEnumerable as IEnumerable__System_Collections_Generic } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections.js";
import type { ICollection, IDictionary, IEnumerable, IEnumerator, IList } from "@tsonic/dotnet/System.Collections.js";
import * as System_ComponentModel_Internal from "@tsonic/dotnet/System.ComponentModel.js";
import type { IComponent, ICustomTypeDescriptor } from "@tsonic/dotnet/System.ComponentModel.js";
import * as System_Data_Common_Internal from "@tsonic/dotnet/System.Data.Common.js";
import type { DbCommand, DbConnection, DbConnectionStringBuilder, DbDataReader, DbException, DbParameter, DbParameterCollection, DbProviderFactory, DbTransaction } from "@tsonic/dotnet/System.Data.Common.js";
import * as System_Data_Internal from "@tsonic/dotnet/System.Data.js";
import type { CommandBehavior, CommandType, ConnectionState, DataTable, DbType, IDataParameter, IDataParameterCollection, IDataReader, IDataRecord, IDbCommand, IDbConnection, IDbDataParameter, IDbTransaction, IsolationLevel, ParameterDirection, UpdateRowSource } from "@tsonic/dotnet/System.Data.js";
import * as System_IO_Internal from "@tsonic/dotnet/System.IO.js";
import type { SeekOrigin, Stream, TextReader } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Array as ClrArray, Boolean as ClrBoolean, Byte, Char, Comparison, DateTime, DateTimeOffset, Decimal, Double, Enum, Func, Guid, IAsyncDisposable, IComparable, IConvertible, IDisposable, IFormattable, Int16, Int32, Int64, ISpanFormattable, Nullable, Object as ClrObject, ReadOnlySpan, Single, Span, String as ClrString, TimeSpan, Type, Void } from "@tsonic/dotnet/System.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { ISerializable } from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";

export enum SqliteCacheMode {
    Default = 0,
    Private = 1,
    Shared = 2
}


export enum SqliteOpenMode {
    ReadWriteCreate = 0,
    ReadWrite = 1,
    ReadOnly = 2,
    Memory = 3
}


export enum SqliteType {
    Integer = 1,
    Real = 2,
    Text = 3,
    Blob = 4
}


export abstract class SqliteBlob$protected {
    protected Dispose(disposing: boolean): void;
}


export interface SqliteBlob$instance extends SqliteBlob$protected, Stream {
    readonly CanRead: boolean;
    readonly CanSeek: boolean;
    readonly CanWrite: boolean;
    readonly Length: long;
    Position: long;
    Flush(): void;
    Read(buffer: byte[], offset: int, count: int): int;
    Read(buffer: Span<System_Internal.Byte>): int;
    Seek(offset: long, origin: SeekOrigin): long;
    SetLength(value: long): void;
    Write(buffer: byte[], offset: int, count: int): void;
    Write(buffer: ReadOnlySpan<System_Internal.Byte>): void;
}


export const SqliteBlob: {
    new(connection: SqliteConnection, tableName: string, columnName: string, rowid: long, readOnly: boolean): SqliteBlob;
    new(connection: SqliteConnection, databaseName: string, tableName: string, columnName: string, rowid: long, readOnly: boolean): SqliteBlob;
};


export type SqliteBlob = SqliteBlob$instance;

export abstract class SqliteCommand$protected {
    protected DataReader: SqliteDataReader | undefined;
    protected DbConnection: DbConnection | undefined;
    protected readonly DbParameterCollection: DbParameterCollection;
    protected DbTransaction: DbTransaction | undefined;
    protected CreateDbParameter(): DbParameter;
    protected Dispose(disposing: boolean): void;
    protected ExecuteDbDataReader(behavior: CommandBehavior): DbDataReader;
    protected ExecuteDbDataReaderAsync(behavior: CommandBehavior, cancellationToken: CancellationToken): Task<DbDataReader>;
}


export interface SqliteCommand$instance extends SqliteCommand$protected, DbCommand {
    CommandText: string;
    CommandTimeout: int;
    CommandType: CommandType;
    get Connection(): SqliteConnection | undefined;
    set Connection(value: SqliteConnection);
    DesignTimeVisible: boolean;
    readonly Parameters: SqliteParameterCollection;
    get Transaction(): SqliteTransaction | undefined;
    set Transaction(value: SqliteTransaction);
    UpdatedRowSource: UpdateRowSource;
    Cancel(): void;
    CreateParameter(): SqliteParameter;
    ExecuteNonQuery(): int;
    ExecuteReader(): SqliteDataReader;
    ExecuteReader(behavior: CommandBehavior): SqliteDataReader;
    ExecuteReaderAsync(): Task<SqliteDataReader>;
    ExecuteReaderAsync(cancellationToken: CancellationToken): Task<SqliteDataReader>;
    ExecuteReaderAsync(behavior: CommandBehavior): Task<SqliteDataReader>;
    ExecuteReaderAsync(behavior: CommandBehavior, cancellationToken: CancellationToken): Task<SqliteDataReader>;
    ExecuteScalar(): unknown | undefined;
    Prepare(): void;
}


export const SqliteCommand: {
    new(): SqliteCommand;
    new(commandText: string): SqliteCommand;
    new(commandText: string, connection: SqliteConnection): SqliteCommand;
    new(commandText: string, connection: SqliteConnection, transaction: SqliteTransaction): SqliteCommand;
};


export type SqliteCommand = SqliteCommand$instance;

export abstract class SqliteConnection$protected {
    protected readonly DbProviderFactory: DbProviderFactory;
    protected Transaction: SqliteTransaction | undefined;
    protected BeginDbTransaction(isolationLevel: IsolationLevel): DbTransaction;
    protected CreateDbCommand(): DbCommand;
    protected Dispose(disposing: boolean): void;
}


export interface SqliteConnection$instance extends SqliteConnection$protected, DbConnection {
    ConnectionString: string;
    readonly Database: string;
    readonly DataSource: string;
    DefaultTimeout: int;
    readonly Handle: sqlite3 | undefined;
    readonly ServerVersion: string;
    readonly State: ConnectionState;
    BackupDatabase(destination: SqliteConnection): void;
    BackupDatabase(destination: SqliteConnection, destinationName: string, sourceName: string): void;
    BeginTransaction(): SqliteTransaction;
    BeginTransaction(deferred: boolean): SqliteTransaction;
    BeginTransaction(isolationLevel: IsolationLevel): SqliteTransaction;
    BeginTransaction(isolationLevel: IsolationLevel, deferred: boolean): SqliteTransaction;
    ChangeDatabase(databaseName: string): void;
    Close(): void;
    CreateAggregate<TAccumulate>(name: string, func: Func<TAccumulate, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, TAccumulate>(name: string, func: Func<TAccumulate, T1, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>, isDeterministic?: boolean): void;
    CreateAggregate<TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    CreateCollation(name: string, comparison: Comparison<System_Internal.String>): void;
    CreateCollation<T>(name: string, state: T, comparison: Func<T, System_Internal.String, System_Internal.String, System_Internal.Int32>): void;
    CreateCommand(): SqliteCommand;
    CreateFunction<TResult>(name: string, function_: Func<TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, TResult>(name: string, function_: Func<T1, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, TResult>(name: string, function_: Func<T1, T2, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, TResult>(name: string, function_: Func<T1, T2, T3, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, TResult>(name: string, function_: Func<T1, T2, T3, T4, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, TResult>(name: string, state: TState, function_: Func<TState, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, TResult>(name: string, state: TState, function_: Func<TState, T1, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>, isDeterministic?: boolean): void;
    EnableExtensions(enable?: boolean): void;
    GetSchema(): DataTable;
    GetSchema(collectionName: string): DataTable;
    GetSchema(collectionName: string, restrictionValues: string[]): DataTable;
    LoadExtension(file: string, proc?: string): void;
    Open(): void;
}


export const SqliteConnection: {
    new(): SqliteConnection;
    new(connectionString: string): SqliteConnection;
    ClearAllPools(): void;
    ClearPool(connection: SqliteConnection): void;
};


export type SqliteConnection = SqliteConnection$instance;

export interface SqliteConnectionStringBuilder$instance extends DbConnectionStringBuilder {
    Cache: SqliteCacheMode;
    DataSource: string;
    DefaultTimeout: int;
    ForeignKeys: Nullable<System_Internal.Boolean>;
    get Item(): unknown | undefined;
    set Item(value: unknown);
    readonly Keys: ICollection;
    Mode: SqliteOpenMode;
    Password: string;
    Pooling: boolean;
    RecursiveTriggers: boolean;
    readonly Values: ICollection;
    get Vfs(): string | undefined;
    set Vfs(value: string);
    Clear(): void;
    ContainsKey(keyword: string): boolean;
    Remove(keyword: string): boolean;
    ShouldSerialize(keyword: string): boolean;
    TryGetValue(keyword: string, value: unknown): boolean;
}


export const SqliteConnectionStringBuilder: {
    new(): SqliteConnectionStringBuilder;
    new(connectionString: string): SqliteConnectionStringBuilder;
};


export type SqliteConnectionStringBuilder = SqliteConnectionStringBuilder$instance;

export abstract class SqliteDataReader$protected {
    protected Dispose(disposing: boolean): void;
}


export interface SqliteDataReader$instance extends SqliteDataReader$protected, DbDataReader {
    readonly Depth: int;
    readonly FieldCount: int;
    readonly Handle: sqlite3_stmt | undefined;
    readonly HasRows: boolean;
    readonly IsClosed: boolean;
    readonly RecordsAffected: int;
    Close(): void;
    get_Item(name: string): unknown;
    get_Item(ordinal: int): unknown;
    GetBoolean(ordinal: int): boolean;
    GetByte(ordinal: int): byte;
    GetBytes(ordinal: int, dataOffset: long, buffer: byte[], bufferOffset: int, length: int): long;
    GetChar(ordinal: int): char;
    GetChars(ordinal: int, dataOffset: long, buffer: char[], bufferOffset: int, length: int): long;
    GetDataTypeName(ordinal: int): string;
    GetDateTime(ordinal: int): DateTime;
    GetDateTimeOffset(ordinal: int): DateTimeOffset;
    GetDecimal(ordinal: int): decimal;
    GetDouble(ordinal: int): double;
    GetEnumerator(): IEnumerator;
    GetFieldType(ordinal: int): Type;
    GetFieldValue<T>(ordinal: int): T;
    GetFloat(ordinal: int): float;
    GetGuid(ordinal: int): Guid;
    GetInt16(ordinal: int): short;
    GetInt32(ordinal: int): int;
    GetInt64(ordinal: int): long;
    GetName(ordinal: int): string;
    GetOrdinal(name: string): int;
    GetSchemaTable(): DataTable;
    GetStream(ordinal: int): Stream;
    GetString(ordinal: int): string;
    GetTextReader(ordinal: int): TextReader;
    GetTimeSpan(ordinal: int): TimeSpan;
    GetValue(ordinal: int): unknown;
    GetValues(values: unknown[]): int;
    IsDBNull(ordinal: int): boolean;
    NextResult(): boolean;
    Read(): boolean;
}


export const SqliteDataReader: {
    new(): SqliteDataReader;
};


export type SqliteDataReader = SqliteDataReader$instance;

export interface SqliteException$instance extends DbException {
    readonly SqliteErrorCode: int;
    readonly SqliteExtendedErrorCode: int;
}


export const SqliteException: {
    new(message: string, errorCode: int): SqliteException;
    new(message: string, errorCode: int, extendedErrorCode: int): SqliteException;
    ThrowExceptionForRC(rc: int, db: sqlite3): void;
};


export type SqliteException = SqliteException$instance;

export interface SqliteFactory$instance extends DbProviderFactory {
    CreateCommand(): DbCommand;
    CreateConnection(): DbConnection;
    CreateConnectionStringBuilder(): DbConnectionStringBuilder;
    CreateParameter(): DbParameter;
}


export const SqliteFactory: {
    new(): SqliteFactory;
    readonly Instance: SqliteFactory;
};


export type SqliteFactory = SqliteFactory$instance;

export interface SqliteParameter$instance extends DbParameter {
    DbType: DbType;
    Direction: ParameterDirection;
    IsNullable: boolean;
    ParameterName: string;
    Size: int;
    SourceColumn: string;
    SourceColumnNullMapping: boolean;
    SqliteType: SqliteType;
    get Value(): unknown | undefined;
    set Value(value: unknown);
    ResetDbType(): void;
    ResetSqliteType(): void;
}


export const SqliteParameter: {
    new(): SqliteParameter;
    new(name: string, value: unknown): SqliteParameter;
    new(name: string, type: SqliteType): SqliteParameter;
    new(name: string, type: SqliteType, size: int): SqliteParameter;
    new(name: string, type: SqliteType, size: int, sourceColumn: string): SqliteParameter;
};


export type SqliteParameter = SqliteParameter$instance;

export abstract class SqliteParameterCollection$protected {
    protected GetParameter(index: int): DbParameter;
    protected GetParameter(parameterName: string): DbParameter;
    protected SetParameter(index: int, value: DbParameter): void;
    protected SetParameter(parameterName: string, value: DbParameter): void;
}


export interface SqliteParameterCollection$instance extends SqliteParameterCollection$protected, DbParameterCollection {
    readonly Count: int;
    readonly SyncRoot: unknown;
    Add(value: unknown): int;
    Add(value: SqliteParameter): SqliteParameter;
    Add(parameterName: string, type: SqliteType): SqliteParameter;
    Add(parameterName: string, type: SqliteType, size: int): SqliteParameter;
    Add(parameterName: string, type: SqliteType, size: int, sourceColumn: string): SqliteParameter;
    AddRange(values: ClrArray): void;
    AddRange(values: IEnumerable__System_Collections_Generic<SqliteParameter>): void;
    AddWithValue(parameterName: string, value: unknown): SqliteParameter;
    Clear(): void;
    Contains(value: unknown): boolean;
    Contains(value: SqliteParameter): boolean;
    Contains(value: string): boolean;
    CopyTo(array: ClrArray, index: int): void;
    CopyTo(array: SqliteParameter[], index: int): void;
    get_Item(index: int): SqliteParameter;
    get_Item(parameterName: string): SqliteParameter;
    GetEnumerator(): IEnumerator;
    IndexOf(value: unknown): int;
    IndexOf(value: SqliteParameter): int;
    IndexOf(parameterName: string): int;
    Insert(index: int, value: unknown): void;
    Insert(index: int, value: SqliteParameter): void;
    Remove(value: unknown): void;
    Remove(value: SqliteParameter): void;
    RemoveAt(index: int): void;
    RemoveAt(parameterName: string): void;
    set_Item(index: int, value: SqliteParameter): void;
    set_Item(parameterName: string, value: SqliteParameter): void;
}


export const SqliteParameterCollection: {
    new(): SqliteParameterCollection;
};


export type SqliteParameterCollection = SqliteParameterCollection$instance;

export abstract class SqliteTransaction$protected {
    protected readonly DbConnection: DbConnection | undefined;
    protected Dispose(disposing: boolean): void;
}


export interface SqliteTransaction$instance extends SqliteTransaction$protected, DbTransaction {
    readonly Connection: SqliteConnection | undefined;
    readonly IsolationLevel: IsolationLevel;
    readonly SupportsSavepoints: boolean;
    Commit(): void;
    Release(savepointName: string): void;
    Rollback(): void;
    Rollback(savepointName: string): void;
    Save(savepointName: string): void;
}


export const SqliteTransaction: {
    new(): SqliteTransaction;
};


export type SqliteTransaction = SqliteTransaction$instance;

