// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Data.Sqlite
// Assembly: Microsoft.Data.Sqlite

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import type { sqlite3, sqlite3_stmt } from "../../SQLitePCL/internal/index.js";
import type { IEnumerable_1 } from "@tsonic/dotnet/System.Collections.Generic/internal/index.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections/internal/index.js";
import type { ICollection, IDictionary, IEnumerable, IEnumerator, IList } from "@tsonic/dotnet/System.Collections/internal/index.js";
import * as System_ComponentModel_Internal from "@tsonic/dotnet/System.ComponentModel/internal/index.js";
import type { IComponent, ICustomTypeDescriptor } from "@tsonic/dotnet/System.ComponentModel/internal/index.js";
import * as System_Data_Common_Internal from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import type { DbCommand, DbConnection, DbConnectionStringBuilder, DbDataReader, DbException, DbParameter, DbParameterCollection, DbProviderFactory, DbTransaction } from "@tsonic/dotnet/System.Data.Common/internal/index.js";
import * as System_Data_Internal from "@tsonic/dotnet/System.Data/internal/index.js";
import type { CommandBehavior, CommandType, ConnectionState, DataTable, DbType, IDataParameter, IDataParameterCollection, IDataReader, IDataRecord, IDbCommand, IDbConnection, IDbDataParameter, IDbTransaction, IsolationLevel, ParameterDirection, UpdateRowSource } from "@tsonic/dotnet/System.Data/internal/index.js";
import * as System_IO_Internal from "@tsonic/dotnet/System.IO/internal/index.js";
import type { SeekOrigin, Stream, TextReader } from "@tsonic/dotnet/System.IO/internal/index.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { ISerializable } from "@tsonic/dotnet/System.Runtime.Serialization/internal/index.js";
import type { Task_1 } from "@tsonic/dotnet/System.Threading.Tasks/internal/index.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading/internal/index.js";
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Array as ClrArray, Boolean as ClrBoolean, Byte, Char, Comparison_1, DateTime, DateTimeOffset, Decimal, Double, Enum, Func_1, Func_10, Func_11, Func_12, Func_13, Func_14, Func_15, Func_16, Func_17, Func_2, Func_3, Func_4, Func_5, Func_6, Func_7, Func_8, Func_9, Guid, IAsyncDisposable, IComparable, IConvertible, IDisposable, IFormattable, Int16, Int32, Int64, ISpanFormattable, Nullable_1, Object as ClrObject, ReadOnlySpan_1, Single, Span_1, String as ClrString, TimeSpan, Type, Void } from "@tsonic/dotnet/System/internal/index.js";

export enum SqliteCacheMode {
    Default = 0,
    Private = 1,
    Shared = 2
}


export enum SqliteOpenMode {
    ReadWriteCreate = 0,
    ReadWrite = 1,
    ReadOnly = 2,
    Memory = 3
}


export enum SqliteType {
    Integer = 1,
    Real = 2,
    Text = 3,
    Blob = 4
}


export interface SqliteBlob$instance extends Stream {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteBlob: never;

    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly CanRead: boolean;
    readonly CanSeek: boolean;
    readonly CanWrite: boolean;
    readonly Length: long;
    Position: long;
    Dispose(disposing: boolean): void;
    Flush(): void;
    Read(buffer: byte[], offset: int, count: int): int;
    Read(buffer: Span_1<System_Internal.Byte>): int;
    Seek(offset: long, origin: SeekOrigin): long;
    SetLength(value: long): void;
    Write(buffer: byte[], offset: int, count: int): void;
    Write(buffer: ReadOnlySpan_1<System_Internal.Byte>): void;
}


export const SqliteBlob: {
    new(connection: SqliteConnection, tableName: string, columnName: string, rowid: long, readOnly: boolean): SqliteBlob;
    new(connection: SqliteConnection, databaseName: string, tableName: string, columnName: string, rowid: long, readOnly: boolean): SqliteBlob;
};


export type SqliteBlob = SqliteBlob$instance;

export interface SqliteCommand$instance extends DbCommand {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteCommand: never;

    readonly __tsonic_iface_System_ComponentModel_IComponent: never;
    readonly __tsonic_iface_System_Data_IDbCommand: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    CommandText: string;
    CommandTimeout: int;
    CommandType: CommandType;
    get Connection(): SqliteConnection | null;
    set Connection(value: SqliteConnection | null);
    get DataReader(): SqliteDataReader | null;
    set DataReader(value: SqliteDataReader | null);
    get DbConnection(): DbConnection | null;
    set DbConnection(value: DbConnection | null);
    readonly DbParameterCollection: DbParameterCollection;
    get DbTransaction(): DbTransaction | null;
    set DbTransaction(value: DbTransaction | null);
    DesignTimeVisible: boolean;
    readonly Parameters: SqliteParameterCollection;
    get Transaction(): SqliteTransaction | null;
    set Transaction(value: SqliteTransaction | null);
    UpdatedRowSource: UpdateRowSource;
    Cancel(): void;
    CreateDbParameter(): DbParameter;
    CreateParameter(): SqliteParameter;
    Dispose(disposing: boolean): void;
    ExecuteDbDataReader(behavior: CommandBehavior): DbDataReader;
    ExecuteDbDataReaderAsync(behavior: CommandBehavior, cancellationToken: CancellationToken): Task_1<DbDataReader>;
    ExecuteNonQuery(): int;
    ExecuteReader(): SqliteDataReader;
    ExecuteReader(behavior: CommandBehavior): SqliteDataReader;
    ExecuteReaderAsync(): Task_1<SqliteDataReader>;
    ExecuteReaderAsync(cancellationToken: CancellationToken): Task_1<SqliteDataReader>;
    ExecuteReaderAsync(behavior: CommandBehavior): Task_1<SqliteDataReader>;
    ExecuteReaderAsync(behavior: CommandBehavior, cancellationToken: CancellationToken): Task_1<SqliteDataReader>;
    ExecuteScalar(): JsValue | null;
    Prepare(): void;
}


export const SqliteCommand: {
    new(): SqliteCommand;
    new(commandText: string | null): SqliteCommand;
    new(commandText: string | null, connection: SqliteConnection | null): SqliteCommand;
    new(commandText: string | null, connection: SqliteConnection | null, transaction: SqliteTransaction | null): SqliteCommand;
};


export type SqliteCommand = SqliteCommand$instance;

export interface SqliteConnection$instance extends DbConnection {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteConnection: never;

    readonly __tsonic_iface_System_ComponentModel_IComponent: never;
    readonly __tsonic_iface_System_Data_IDbConnection: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    ConnectionString: string;
    readonly Database: string;
    readonly DataSource: string;
    readonly DbProviderFactory: DbProviderFactory;
    DefaultTimeout: int;
    readonly Handle: sqlite3 | null;
    readonly ServerVersion: string;
    readonly State: ConnectionState;
    get Transaction(): SqliteTransaction | null;
    set Transaction(value: SqliteTransaction | null);
    BackupDatabase(destination: SqliteConnection): void;
    BackupDatabase(destination: SqliteConnection, destinationName: string, sourceName: string): void;
    BeginDbTransaction(isolationLevel: IsolationLevel): DbTransaction;
    BeginTransaction(): SqliteTransaction;
    BeginTransaction(deferred: boolean): SqliteTransaction;
    BeginTransaction(isolationLevel: IsolationLevel): SqliteTransaction;
    BeginTransaction(isolationLevel: IsolationLevel, deferred: boolean): SqliteTransaction;
    ChangeDatabase(databaseName: string): void;
    Close(): void;
    CreateAggregate<TAccumulate>(name: string, func: Func_2<TAccumulate | null, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, TAccumulate>(name: string, func: Func_3<TAccumulate | null, T1, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, TAccumulate>(name: string, func: Func_4<TAccumulate | null, T1, T2, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, TAccumulate>(name: string, func: Func_5<TAccumulate | null, T1, T2, T3, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, TAccumulate>(name: string, func: Func_6<TAccumulate | null, T1, T2, T3, T4, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, TAccumulate>(name: string, func: Func_7<TAccumulate | null, T1, T2, T3, T4, T5, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, TAccumulate>(name: string, func: Func_8<TAccumulate | null, T1, T2, T3, T4, T5, T6, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, TAccumulate>(name: string, func: Func_9<TAccumulate | null, T1, T2, T3, T4, T5, T6, T7, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>(name: string, func: Func_10<TAccumulate | null, T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>(name: string, func: Func_11<TAccumulate | null, T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>(name: string, func: Func_12<TAccumulate | null, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>(name: string, func: Func_13<TAccumulate | null, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>(name: string, func: Func_14<TAccumulate | null, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>(name: string, func: Func_15<TAccumulate | null, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>(name: string, func: Func_16<TAccumulate | null, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>(name: string, func: Func_17<TAccumulate | null, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<TAccumulate>(name: string, seed: TAccumulate, func: Func_2<TAccumulate, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, TAccumulate>(name: string, seed: TAccumulate, func: Func_3<TAccumulate, T1, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, TAccumulate>(name: string, seed: TAccumulate, func: Func_4<TAccumulate, T1, T2, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, TAccumulate>(name: string, seed: TAccumulate, func: Func_5<TAccumulate, T1, T2, T3, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, TAccumulate>(name: string, seed: TAccumulate, func: Func_6<TAccumulate, T1, T2, T3, T4, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, TAccumulate>(name: string, seed: TAccumulate, func: Func_7<TAccumulate, T1, T2, T3, T4, T5, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, TAccumulate>(name: string, seed: TAccumulate, func: Func_8<TAccumulate, T1, T2, T3, T4, T5, T6, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, TAccumulate>(name: string, seed: TAccumulate, func: Func_9<TAccumulate, T1, T2, T3, T4, T5, T6, T7, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>(name: string, seed: TAccumulate, func: Func_10<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>(name: string, seed: TAccumulate, func: Func_11<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>(name: string, seed: TAccumulate, func: Func_12<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>(name: string, seed: TAccumulate, func: Func_13<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>(name: string, seed: TAccumulate, func: Func_14<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>(name: string, seed: TAccumulate, func: Func_15<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>(name: string, seed: TAccumulate, func: Func_16<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>(name: string, seed: TAccumulate, func: Func_17<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate> | null, isDeterministic?: boolean): void;
    CreateAggregate<TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_2<TAccumulate, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_3<TAccumulate, T1, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_4<TAccumulate, T1, T2, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_5<TAccumulate, T1, T2, T3, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_6<TAccumulate, T1, T2, T3, T4, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_7<TAccumulate, T1, T2, T3, T4, T5, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_8<TAccumulate, T1, T2, T3, T4, T5, T6, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_9<TAccumulate, T1, T2, T3, T4, T5, T6, T7, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_10<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_11<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_12<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_13<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_14<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_15<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_16<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func_17<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate> | null, resultSelector: Func_2<TAccumulate, TResult> | null, isDeterministic?: boolean): void;
    CreateCollation(name: string, comparison: Comparison_1<System_Internal.String> | null): void;
    CreateCollation<T>(name: string, state: T, comparison: Func_4<T, System_Internal.String, System_Internal.String, System_Internal.Int32> | null): void;
    CreateCommand(): SqliteCommand;
    CreateDbCommand(): DbCommand;
    CreateFunction<TResult>(name: string, function_: Func_1<TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, TResult>(name: string, function_: Func_2<T1, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, TResult>(name: string, function_: Func_3<T1, T2, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, TResult>(name: string, function_: Func_4<T1, T2, T3, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, TResult>(name: string, function_: Func_5<T1, T2, T3, T4, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, TResult>(name: string, function_: Func_6<T1, T2, T3, T4, T5, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, TResult>(name: string, function_: Func_7<T1, T2, T3, T4, T5, T6, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, TResult>(name: string, function_: Func_8<T1, T2, T3, T4, T5, T6, T7, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(name: string, function_: Func_9<T1, T2, T3, T4, T5, T6, T7, T8, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(name: string, function_: Func_10<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(name: string, function_: Func_11<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(name: string, function_: Func_12<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(name: string, function_: Func_13<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(name: string, function_: Func_14<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(name: string, function_: Func_15<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(name: string, function_: Func_16<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult>(name: string, function_: Func_17<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, TResult>(name: string, state: TState, function_: Func_2<TState, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, TResult>(name: string, state: TState, function_: Func_3<TState, T1, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, TResult>(name: string, state: TState, function_: Func_4<TState, T1, T2, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, TResult>(name: string, state: TState, function_: Func_5<TState, T1, T2, T3, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, TResult>(name: string, state: TState, function_: Func_6<TState, T1, T2, T3, T4, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, TResult>(name: string, state: TState, function_: Func_7<TState, T1, T2, T3, T4, T5, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, TResult>(name: string, state: TState, function_: Func_8<TState, T1, T2, T3, T4, T5, T6, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, TResult>(name: string, state: TState, function_: Func_9<TState, T1, T2, T3, T4, T5, T6, T7, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, TResult>(name: string, state: TState, function_: Func_10<TState, T1, T2, T3, T4, T5, T6, T7, T8, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(name: string, state: TState, function_: Func_11<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(name: string, state: TState, function_: Func_12<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(name: string, state: TState, function_: Func_13<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(name: string, state: TState, function_: Func_14<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(name: string, state: TState, function_: Func_15<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(name: string, state: TState, function_: Func_16<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult> | null, isDeterministic?: boolean): void;
    CreateFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(name: string, state: TState, function_: Func_17<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult> | null, isDeterministic?: boolean): void;
    Dispose(disposing: boolean): void;
    EnableExtensions(enable?: boolean): void;
    GetSchema(): DataTable;
    GetSchema(collectionName: string): DataTable;
    GetSchema(collectionName: string, restrictionValues: (string | null)[]): DataTable;
    LoadExtension(file: string, proc?: string | null): void;
    Open(): void;
}


export const SqliteConnection: {
    new(): SqliteConnection;
    new(connectionString: string | null): SqliteConnection;
    ClearAllPools(): void;
    ClearPool(connection: SqliteConnection): void;
};


export type SqliteConnection = SqliteConnection$instance;

export interface SqliteConnectionStringBuilder$instance extends DbConnectionStringBuilder {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteConnectionStringBuilder: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IDictionary: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_ComponentModel_ICustomTypeDescriptor: never;

    Cache: SqliteCacheMode;
    DataSource: string;
    DefaultTimeout: int;
    get ForeignKeys(): Nullable_1<System_Internal.Boolean>;
    set ForeignKeys(value: Nullable_1<System_Internal.Boolean> | boolean);
    readonly Keys: ICollection;
    Mode: SqliteOpenMode;
    Password: string;
    Pooling: boolean;
    RecursiveTriggers: boolean;
    readonly Values: ICollection;
    get Vfs(): string | null;
    set Vfs(value: string | null);
    Clear(): void;
    ContainsKey(keyword: string): boolean;
    Remove(keyword: string): boolean;
    ShouldSerialize(keyword: string): boolean;
    TryGetValue(keyword: string, value: JsValue | null): boolean;
}


export const SqliteConnectionStringBuilder: {
    new(): SqliteConnectionStringBuilder;
    new(connectionString: string | null): SqliteConnectionStringBuilder;
};


export type SqliteConnectionStringBuilder = SqliteConnectionStringBuilder$instance & { [keyword: string]: JsValue | null; };

export interface SqliteDataReader$instance extends DbDataReader {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteDataReader: never;

    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Data_IDataReader: never;
    readonly __tsonic_iface_System_Data_IDataRecord: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Depth: int;
    readonly FieldCount: int;
    readonly Handle: sqlite3_stmt | null;
    readonly HasRows: boolean;
    readonly IsClosed: boolean;
    readonly RecordsAffected: int;
    Close(): void;
    Dispose(disposing: boolean): void;
    get_Item(name: string): JsValue;
    get_Item(ordinal: int): JsValue;
    GetBoolean(ordinal: int): boolean;
    GetByte(ordinal: int): byte;
    GetBytes(ordinal: int, dataOffset: long, buffer: byte[] | null, bufferOffset: int, length: int): long;
    GetChar(ordinal: int): char;
    GetChars(ordinal: int, dataOffset: long, buffer: char[] | null, bufferOffset: int, length: int): long;
    GetDataTypeName(ordinal: int): string;
    GetDateTime(ordinal: int): DateTime;
    GetDateTimeOffset(ordinal: int): DateTimeOffset;
    GetDecimal(ordinal: int): decimal;
    GetDouble(ordinal: int): double;
    GetEnumerator(): IEnumerator;
    GetFieldType(ordinal: int): Type;
    GetFieldValue<T>(ordinal: int): T;
    GetFloat(ordinal: int): float;
    GetGuid(ordinal: int): Guid;
    GetInt16(ordinal: int): short;
    GetInt32(ordinal: int): int;
    GetInt64(ordinal: int): long;
    GetName(ordinal: int): string;
    GetOrdinal(name: string): int;
    GetSchemaTable(): DataTable;
    GetStream(ordinal: int): Stream;
    GetString(ordinal: int): string;
    GetTextReader(ordinal: int): TextReader;
    GetTimeSpan(ordinal: int): TimeSpan;
    GetValue(ordinal: int): JsValue;
    GetValues(values: (JsValue | null)[]): int;
    IsDBNull(ordinal: int): boolean;
    NextResult(): boolean;
    Read(): boolean;
}


export const SqliteDataReader: {
};


export type SqliteDataReader = SqliteDataReader$instance;

export interface SqliteException$instance extends DbException {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteException: never;

    readonly __tsonic_iface_System_Runtime_Serialization_ISerializable: never;

    readonly SqliteErrorCode: int;
    readonly SqliteExtendedErrorCode: int;
}


export const SqliteException: {
    new(message: string | null, errorCode: int): SqliteException;
    new(message: string | null, errorCode: int, extendedErrorCode: int): SqliteException;
    ThrowExceptionForRC(rc: int, db: sqlite3 | null): void;
};


export type SqliteException = SqliteException$instance;

export interface SqliteFactory$instance extends DbProviderFactory {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteFactory: never;

    CreateCommand(): DbCommand;
    CreateConnection(): DbConnection;
    CreateConnectionStringBuilder(): DbConnectionStringBuilder;
    CreateParameter(): DbParameter;
}


export const SqliteFactory: {
    readonly Instance: SqliteFactory;
};


export type SqliteFactory = SqliteFactory$instance;

export interface SqliteParameter$instance extends DbParameter {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteParameter: never;

    readonly __tsonic_iface_System_Data_IDataParameter: never;
    readonly __tsonic_iface_System_Data_IDbDataParameter: never;

    DbType: DbType;
    Direction: ParameterDirection;
    IsNullable: boolean;
    ParameterName: string;
    Size: int;
    SourceColumn: string;
    SourceColumnNullMapping: boolean;
    SqliteType: SqliteType;
    get Value(): JsValue | null;
    set Value(value: JsValue | null);
    ResetDbType(): void;
    ResetSqliteType(): void;
}


export const SqliteParameter: {
    new(): SqliteParameter;
    new(name: string | null, value: JsValue | null): SqliteParameter;
    new(name: string | null, type: SqliteType): SqliteParameter;
    new(name: string | null, type: SqliteType, size: int): SqliteParameter;
    new(name: string | null, type: SqliteType, size: int, sourceColumn: string | null): SqliteParameter;
};


export type SqliteParameter = SqliteParameter$instance;

export interface SqliteParameterCollection$instance extends DbParameterCollection {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteParameterCollection: never;

    readonly __tsonic_iface_System_Collections_ICollection: never;
    readonly __tsonic_iface_System_Collections_IEnumerable: never;
    readonly __tsonic_iface_System_Collections_IList: never;
    readonly __tsonic_iface_System_Data_IDataParameterCollection: never;

    readonly Count: int;
    readonly SyncRoot: JsValue;
    Add(value: JsValue): int;
    Add(value: SqliteParameter): SqliteParameter;
    Add(parameterName: string | null, type: SqliteType): SqliteParameter;
    Add(parameterName: string | null, type: SqliteType, size: int): SqliteParameter;
    Add(parameterName: string | null, type: SqliteType, size: int, sourceColumn: string | null): SqliteParameter;
    AddRange(values: ClrArray): void;
    AddRange(values: IEnumerable_1<SqliteParameter>): void;
    AddWithValue(parameterName: string | null, value: JsValue | null): SqliteParameter;
    Clear(): void;
    Contains(value: JsValue): boolean;
    Contains(value: SqliteParameter): boolean;
    Contains(value: string): boolean;
    CopyTo(array: ClrArray, index: int): void;
    CopyTo(array: SqliteParameter[], index: int): void;
    get_Item(index: int): SqliteParameter;
    get_Item(parameterName: string): SqliteParameter;
    GetEnumerator(): IEnumerator;
    GetParameter(index: int): DbParameter;
    GetParameter(parameterName: string): DbParameter;
    IndexOf(value: JsValue): int;
    IndexOf(value: SqliteParameter): int;
    IndexOf(parameterName: string): int;
    Insert(index: int, value: JsValue): void;
    Insert(index: int, value: SqliteParameter): void;
    Remove(value: JsValue): void;
    Remove(value: SqliteParameter): void;
    RemoveAt(index: int): void;
    RemoveAt(parameterName: string): void;
    set_Item(index: int, value: SqliteParameter): void;
    set_Item(parameterName: string, value: SqliteParameter): void;
    SetParameter(index: int, value: DbParameter): void;
    SetParameter(parameterName: string, value: DbParameter): void;
}


export const SqliteParameterCollection: (abstract new() => SqliteParameterCollection) & {
};


export type SqliteParameterCollection = SqliteParameterCollection$instance;

export interface SqliteTransaction$instance extends DbTransaction {
    readonly __tsonic_type_Microsoft_Data_Sqlite_SqliteTransaction: never;

    readonly __tsonic_iface_System_Data_IDbTransaction: never;
    readonly __tsonic_iface_System_IAsyncDisposable: never;
    readonly __tsonic_iface_System_IDisposable: never;

    readonly Connection: SqliteConnection | null;
    readonly DbConnection: DbConnection | null;
    readonly IsolationLevel: IsolationLevel;
    readonly SupportsSavepoints: boolean;
    Commit(): void;
    Dispose(disposing: boolean): void;
    Release(savepointName: string): void;
    Rollback(): void;
    Rollback(savepointName: string): void;
    Save(savepointName: string): void;
}


export const SqliteTransaction: {
};


export type SqliteTransaction = SqliteTransaction$instance;

