// Generated by tsbindgen - Architecture
// Namespace: Microsoft.Data.Sqlite
// Assembly: Microsoft.Data.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import support types from @tsonic/core
import type { ptr } from "@tsonic/core/types.js";

// Import types from other namespaces
import type { sqlite3, sqlite3_stmt } from "../../SQLitePCL/internal/index.js";
import type { IEnumerable as IEnumerable__System_Collections_Generic } from "@tsonic/dotnet/System.Collections.Generic.js";
import * as System_Collections_Internal from "@tsonic/dotnet/System.Collections.js";
import type { ICollection, IDictionary, IEnumerable, IEnumerator, IList } from "@tsonic/dotnet/System.Collections.js";
import * as System_ComponentModel_Internal from "@tsonic/dotnet/System.ComponentModel.js";
import type { IComponent, ICustomTypeDescriptor } from "@tsonic/dotnet/System.ComponentModel.js";
import * as System_Data_Common_Internal from "@tsonic/dotnet/System.Data.Common.js";
import type { DbCommand, DbConnection, DbConnectionStringBuilder, DbDataReader, DbException, DbParameter, DbParameterCollection, DbProviderFactory, DbTransaction } from "@tsonic/dotnet/System.Data.Common.js";
import * as System_Data_Internal from "@tsonic/dotnet/System.Data.js";
import type { CommandBehavior, CommandType, ConnectionState, DataTable, DbType, IDataParameter, IDataParameterCollection, IDataReader, IDataRecord, IDbCommand, IDbConnection, IDbDataParameter, IDbTransaction, IsolationLevel, ParameterDirection, UpdateRowSource } from "@tsonic/dotnet/System.Data.js";
import * as System_IO_Internal from "@tsonic/dotnet/System.IO.js";
import type { SeekOrigin, Stream, TextReader } from "@tsonic/dotnet/System.IO.js";
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Array as ClrArray, Boolean as ClrBoolean, Byte, Char, Comparison, DateTime, DateTimeOffset, Decimal, Double, Enum, Func, Guid, IAsyncDisposable, IComparable, IConvertible, IDisposable, IFormattable, Int16, Int32, Int64, ISpanFormattable, Nullable, Object as ClrObject, ReadOnlySpan, Single, Span, String as ClrString, TimeSpan, Type, Void } from "@tsonic/dotnet/System.js";
import * as System_Runtime_Serialization_Internal from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { ISerializable } from "@tsonic/dotnet/System.Runtime.Serialization.js";
import type { CancellationToken } from "@tsonic/dotnet/System.Threading.js";
import type { Task } from "@tsonic/dotnet/System.Threading.Tasks.js";

export enum SqliteCacheMode {
    default = 0,
    private = 1,
    shared = 2
}


export enum SqliteOpenMode {
    readWriteCreate = 0,
    readWrite = 1,
    readOnly = 2,
    memory = 3
}


export enum SqliteType {
    integer = 1,
    real = 2,
    text = 3,
    blob = 4
}


export interface SqliteBlob$instance extends Stream {
    readonly canRead: boolean;
    readonly canSeek: boolean;
    readonly canWrite: boolean;
    readonly length: long;
    position: long;
    flush(): void;
    read(buffer: byte[], offset: int, count: int): int;
    read(buffer: Span<System_Internal.Byte>): int;
    seek(offset: long, origin: SeekOrigin): long;
    setLength(value: long): void;
    write(buffer: byte[], offset: int, count: int): void;
    write(buffer: ReadOnlySpan<System_Internal.Byte>): void;
}


export const SqliteBlob: {
    new(connection: SqliteConnection, tableName: string, columnName: string, rowid: long, readOnly: boolean): SqliteBlob;
    new(connection: SqliteConnection, databaseName: string, tableName: string, columnName: string, rowid: long, readOnly: boolean): SqliteBlob;
};


export type SqliteBlob = SqliteBlob$instance;

export interface SqliteCommand$instance extends DbCommand {
    commandText: string;
    commandTimeout: int;
    commandType: CommandType;
    get connection(): SqliteConnection | undefined;
    set connection(value: SqliteConnection);
    designTimeVisible: boolean;
    readonly parameters: SqliteParameterCollection;
    get transaction(): SqliteTransaction | undefined;
    set transaction(value: SqliteTransaction);
    updatedRowSource: UpdateRowSource;
    cancel(): void;
    createParameter(): SqliteParameter;
    executeNonQuery(): int;
    executeReader(): SqliteDataReader;
    executeReader(behavior: CommandBehavior): SqliteDataReader;
    executeReaderAsync(): Task<SqliteDataReader>;
    executeReaderAsync(cancellationToken: CancellationToken): Task<SqliteDataReader>;
    executeReaderAsync(behavior: CommandBehavior): Task<SqliteDataReader>;
    executeReaderAsync(behavior: CommandBehavior, cancellationToken: CancellationToken): Task<SqliteDataReader>;
    executeScalar(): unknown | undefined;
    prepare(): void;
}


export const SqliteCommand: {
    new(): SqliteCommand;
    new(commandText: string): SqliteCommand;
    new(commandText: string, connection: SqliteConnection): SqliteCommand;
    new(commandText: string, connection: SqliteConnection, transaction: SqliteTransaction): SqliteCommand;
};


export type SqliteCommand = SqliteCommand$instance;

export interface SqliteConnection$instance extends DbConnection {
    connectionString: string;
    readonly database: string;
    readonly dataSource: string;
    defaultTimeout: int;
    readonly handle: sqlite3 | undefined;
    readonly serverVersion: string;
    readonly state: ConnectionState;
    backupDatabase(destination: SqliteConnection): void;
    backupDatabase(destination: SqliteConnection, destinationName: string, sourceName: string): void;
    beginTransaction(): SqliteTransaction;
    beginTransaction(deferred: boolean): SqliteTransaction;
    beginTransaction(isolationLevel: IsolationLevel): SqliteTransaction;
    beginTransaction(isolationLevel: IsolationLevel, deferred: boolean): SqliteTransaction;
    changeDatabase(databaseName: string): void;
    close(): void;
    createAggregate<TAccumulate>(name: string, func: Func<TAccumulate, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, TAccumulate>(name: string, func: Func<TAccumulate, T1, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>(name: string, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>, isDeterministic?: boolean): void;
    createAggregate<TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createAggregate<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate, TResult>(name: string, seed: TAccumulate, func: Func<TAccumulate, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TAccumulate>, resultSelector: Func<TAccumulate, TResult>, isDeterministic?: boolean): void;
    createCollation(name: string, comparison: Comparison<System_Internal.String>): void;
    createCollation<T>(name: string, state: T, comparison: Func<T, System_Internal.String, System_Internal.String, System_Internal.Int32>): void;
    createCommand(): SqliteCommand;
    createFunction<TResult>(name: string, function_: Func<TResult>, isDeterministic?: boolean): void;
    createFunction<T1, TResult>(name: string, function_: Func<T1, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, TResult>(name: string, function_: Func<T1, T2, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, TResult>(name: string, function_: Func<T1, T2, T3, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, TResult>(name: string, function_: Func<T1, T2, T3, T4, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>, isDeterministic?: boolean): void;
    createFunction<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult>(name: string, function_: Func<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, TResult>(name: string, state: TState, function_: Func<TState, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, TResult>(name: string, state: TState, function_: Func<TState, T1, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, T7, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, TResult>, isDeterministic?: boolean): void;
    createFunction<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>(name: string, state: TState, function_: Func<TState, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, TResult>, isDeterministic?: boolean): void;
    enableExtensions(enable?: boolean): void;
    getSchema(): DataTable;
    getSchema(collectionName: string): DataTable;
    getSchema(collectionName: string, restrictionValues: string[]): DataTable;
    loadExtension(file: string, proc?: string): void;
    open(): void;
}


export const SqliteConnection: {
    new(): SqliteConnection;
    new(connectionString: string): SqliteConnection;
    clearAllPools(): void;
    clearPool(connection: SqliteConnection): void;
};


export type SqliteConnection = SqliteConnection$instance;

export interface SqliteConnectionStringBuilder$instance extends DbConnectionStringBuilder {
    cache: SqliteCacheMode;
    dataSource: string;
    defaultTimeout: int;
    foreignKeys: Nullable<System_Internal.Boolean>;
    get item(): unknown | undefined;
    set item(value: unknown);
    readonly keys: ICollection;
    mode: SqliteOpenMode;
    password: string;
    pooling: boolean;
    recursiveTriggers: boolean;
    readonly values: ICollection;
    get vfs(): string | undefined;
    set vfs(value: string);
    clear(): void;
    containsKey(keyword: string): boolean;
    remove(keyword: string): boolean;
    shouldSerialize(keyword: string): boolean;
    tryGetValue(keyword: string, value: unknown): boolean;
}


export const SqliteConnectionStringBuilder: {
    new(): SqliteConnectionStringBuilder;
    new(connectionString: string): SqliteConnectionStringBuilder;
};


export type SqliteConnectionStringBuilder = SqliteConnectionStringBuilder$instance;

export interface SqliteDataReader$instance extends DbDataReader {
    readonly depth: int;
    readonly fieldCount: int;
    readonly handle: sqlite3_stmt | undefined;
    readonly hasRows: boolean;
    readonly isClosed: boolean;
    readonly recordsAffected: int;
    close(): void;
    get_Item(name: string): unknown;
    get_Item(ordinal: int): unknown;
    getBoolean(ordinal: int): boolean;
    getByte(ordinal: int): byte;
    getBytes(ordinal: int, dataOffset: long, buffer: byte[], bufferOffset: int, length: int): long;
    getChar(ordinal: int): char;
    getChars(ordinal: int, dataOffset: long, buffer: char[], bufferOffset: int, length: int): long;
    getDataTypeName(ordinal: int): string;
    getDateTime(ordinal: int): DateTime;
    getDateTimeOffset(ordinal: int): DateTimeOffset;
    getDecimal(ordinal: int): decimal;
    getDouble(ordinal: int): double;
    getEnumerator(): IEnumerator;
    getFieldType(ordinal: int): Type;
    getFieldValue<T>(ordinal: int): T;
    getFloat(ordinal: int): float;
    getGuid(ordinal: int): Guid;
    getInt16(ordinal: int): short;
    getInt32(ordinal: int): int;
    getInt64(ordinal: int): long;
    getName(ordinal: int): string;
    getOrdinal(name: string): int;
    getSchemaTable(): DataTable;
    getStream(ordinal: int): Stream;
    getString(ordinal: int): string;
    getTextReader(ordinal: int): TextReader;
    getTimeSpan(ordinal: int): TimeSpan;
    getValue(ordinal: int): unknown;
    getValues(values: unknown[]): int;
    isDBNull(ordinal: int): boolean;
    nextResult(): boolean;
    read(): boolean;
}


export const SqliteDataReader: {
    new(): SqliteDataReader;
};


export type SqliteDataReader = SqliteDataReader$instance;

export interface SqliteException$instance extends DbException {
    readonly sqliteErrorCode: int;
    readonly sqliteExtendedErrorCode: int;
}


export const SqliteException: {
    new(message: string, errorCode: int): SqliteException;
    new(message: string, errorCode: int, extendedErrorCode: int): SqliteException;
    throwExceptionForRC(rc: int, db: sqlite3): void;
};


export type SqliteException = SqliteException$instance;

export interface SqliteFactory$instance extends DbProviderFactory {
    createCommand(): DbCommand;
    createConnection(): DbConnection;
    createConnectionStringBuilder(): DbConnectionStringBuilder;
    createParameter(): DbParameter;
}


export const SqliteFactory: {
    new(): SqliteFactory;
    readonly instance: SqliteFactory;
};


export type SqliteFactory = SqliteFactory$instance;

export interface SqliteParameter$instance extends DbParameter {
    dbType: DbType;
    direction: ParameterDirection;
    isNullable: boolean;
    parameterName: string;
    size: int;
    sourceColumn: string;
    sourceColumnNullMapping: boolean;
    sqliteType: SqliteType;
    get value(): unknown | undefined;
    set value(value: unknown);
    resetDbType(): void;
    resetSqliteType(): void;
}


export const SqliteParameter: {
    new(): SqliteParameter;
    new(name: string, value: unknown): SqliteParameter;
    new(name: string, type: SqliteType): SqliteParameter;
    new(name: string, type: SqliteType, size: int): SqliteParameter;
    new(name: string, type: SqliteType, size: int, sourceColumn: string): SqliteParameter;
};


export type SqliteParameter = SqliteParameter$instance;

export interface SqliteParameterCollection$instance extends DbParameterCollection {
    readonly count: int;
    readonly syncRoot: unknown;
    add(value: unknown): int;
    add(value: SqliteParameter): SqliteParameter;
    add(parameterName: string, type: SqliteType): SqliteParameter;
    add(parameterName: string, type: SqliteType, size: int): SqliteParameter;
    add(parameterName: string, type: SqliteType, size: int, sourceColumn: string): SqliteParameter;
    addRange(values: ClrArray): void;
    addRange(values: IEnumerable__System_Collections_Generic<SqliteParameter>): void;
    addWithValue(parameterName: string, value: unknown): SqliteParameter;
    clear(): void;
    contains(value: unknown): boolean;
    contains(value: SqliteParameter): boolean;
    contains(value: string): boolean;
    copyTo(array: ClrArray, index: int): void;
    copyTo(array: SqliteParameter[], index: int): void;
    get_Item(index: int): SqliteParameter;
    get_Item(parameterName: string): SqliteParameter;
    getEnumerator(): IEnumerator;
    indexOf(value: unknown): int;
    indexOf(value: SqliteParameter): int;
    indexOf(parameterName: string): int;
    insert(index: int, value: unknown): void;
    insert(index: int, value: SqliteParameter): void;
    remove(value: unknown): void;
    remove(value: SqliteParameter): void;
    removeAt(index: int): void;
    removeAt(parameterName: string): void;
    set_Item(index: int, value: SqliteParameter): void;
    set_Item(parameterName: string, value: SqliteParameter): void;
}


export const SqliteParameterCollection: {
    new(): SqliteParameterCollection;
};


export type SqliteParameterCollection = SqliteParameterCollection$instance;

export interface SqliteTransaction$instance extends DbTransaction {
    readonly connection: SqliteConnection | undefined;
    readonly isolationLevel: IsolationLevel;
    readonly supportsSavepoints: boolean;
    commit(): void;
    release(savepointName: string): void;
    rollback(): void;
    rollback(savepointName: string): void;
    save(savepointName: string): void;
}


export const SqliteTransaction: {
    new(): SqliteTransaction;
};


export type SqliteTransaction = SqliteTransaction$instance;

