// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Primitive type aliases from @tsonic/core
import type { sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';

// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System.js";
import type { Func, String as ClrString, Type } from "@tsonic/dotnet/System.js";
import * as Microsoft_EntityFrameworkCore_Diagnostics_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";
import type { EventData, EventDefinitionBase, RelationalLoggingDefinitions } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics.js";

export interface SqliteLoggingDefinitions$instance extends RelationalLoggingDefinitions {
    logSchemaConfigured: EventDefinitionBase | undefined;
    logSequenceConfigured: EventDefinitionBase | undefined;
    logUsingSchemaSelectionsWarning: EventDefinitionBase | undefined;
    logFoundColumn: EventDefinitionBase | undefined;
    logFoundForeignKey: EventDefinitionBase | undefined;
    logForeignKeyScaffoldErrorPrincipalTableNotFound: EventDefinitionBase | undefined;
    logFoundTable: EventDefinitionBase | undefined;
    logMissingTable: EventDefinitionBase | undefined;
    logPrincipalColumnNotFound: EventDefinitionBase | undefined;
    logFoundIndex: EventDefinitionBase | undefined;
    logFoundPrimaryKey: EventDefinitionBase | undefined;
    logFoundUniqueConstraint: EventDefinitionBase | undefined;
    logUnexpectedConnectionType: EventDefinitionBase | undefined;
    logTableRebuildPendingWarning: EventDefinitionBase | undefined;
    logCompositeKeyWithValueGeneration: EventDefinitionBase | undefined;
    logConflictingValueGenerationStrategies: EventDefinitionBase | undefined;
    logInferringTypes: EventDefinitionBase | undefined;
    logOutOfRangeWarning: EventDefinitionBase | undefined;
    logFormatWarning: EventDefinitionBase | undefined;
}


export const SqliteLoggingDefinitions: {
    new(): SqliteLoggingDefinitions;
};


export type SqliteLoggingDefinitions = SqliteLoggingDefinitions$instance;

export interface TableRebuildEventData$instance extends EventData {
    readonly operationType: Type;
    readonly tableName: string | undefined;
}


export const TableRebuildEventData: {
    new(eventDefinition: EventDefinitionBase, messageGenerator: Func<EventDefinitionBase, EventData, System_Internal.String>, operationType: Type, tableName: string): TableRebuildEventData;
};


export type TableRebuildEventData = TableRebuildEventData$instance;

export interface UnexpectedConnectionTypeEventData$instance extends EventData {
    readonly connectionType: Type;
}


export const UnexpectedConnectionTypeEventData: {
    new(eventDefinition: EventDefinitionBase, messageGenerator: Func<EventDefinitionBase, EventData, System_Internal.String>, connectionType: Type): UnexpectedConnectionTypeEventData;
};


export type UnexpectedConnectionTypeEventData = UnexpectedConnectionTypeEventData$instance;

