// Generated by tsbindgen - Architecture
// Namespace: Microsoft.EntityFrameworkCore.Sqlite.Diagnostics.Internal
// Assembly: Microsoft.EntityFrameworkCore.Sqlite

// Core type aliases from @tsonic/core
import type { JsValue, fnptr, ptr, sbyte, byte, short, ushort, int, uint, long, ulong, int128, uint128, half, float, double, decimal, nint, nuint, char } from '@tsonic/core/types.js';


// Import types from other namespaces
import * as System_Internal from "@tsonic/dotnet/System/internal/index.js";
import type { Func_3, String as ClrString, Type } from "@tsonic/dotnet/System/internal/index.js";
import * as Microsoft_EntityFrameworkCore_Diagnostics_Internal from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";
import type { EventData, EventDefinitionBase, RelationalLoggingDefinitions } from "@tsonic/efcore/Microsoft.EntityFrameworkCore.Diagnostics/internal/index.js";

export interface SqliteLoggingDefinitions$instance extends RelationalLoggingDefinitions {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Sqlite_Diagnostics_Internal_SqliteLoggingDefinitions: never;

    LogSchemaConfigured: EventDefinitionBase | null;
    LogSequenceConfigured: EventDefinitionBase | null;
    LogUsingSchemaSelectionsWarning: EventDefinitionBase | null;
    LogFoundColumn: EventDefinitionBase | null;
    LogFoundForeignKey: EventDefinitionBase | null;
    LogForeignKeyScaffoldErrorPrincipalTableNotFound: EventDefinitionBase | null;
    LogFoundTable: EventDefinitionBase | null;
    LogMissingTable: EventDefinitionBase | null;
    LogPrincipalColumnNotFound: EventDefinitionBase | null;
    LogFoundIndex: EventDefinitionBase | null;
    LogFoundPrimaryKey: EventDefinitionBase | null;
    LogFoundUniqueConstraint: EventDefinitionBase | null;
    LogUnexpectedConnectionType: EventDefinitionBase | null;
    LogTableRebuildPendingWarning: EventDefinitionBase | null;
    LogCompositeKeyWithValueGeneration: EventDefinitionBase | null;
    LogConflictingValueGenerationStrategies: EventDefinitionBase | null;
    LogInferringTypes: EventDefinitionBase | null;
    LogOutOfRangeWarning: EventDefinitionBase | null;
    LogFormatWarning: EventDefinitionBase | null;
}


export const SqliteLoggingDefinitions: {
    new(): SqliteLoggingDefinitions;
};


export type SqliteLoggingDefinitions = SqliteLoggingDefinitions$instance;

export interface TableRebuildEventData$instance extends EventData {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Sqlite_Diagnostics_Internal_TableRebuildEventData: never;

    readonly OperationType: Type;
    readonly TableName: string | null;
}


export const TableRebuildEventData: {
    new(eventDefinition: EventDefinitionBase, messageGenerator: Func_3<EventDefinitionBase, EventData, System_Internal.String>, operationType: Type, tableName: string | null): TableRebuildEventData;
};


export type TableRebuildEventData = TableRebuildEventData$instance;

export interface UnexpectedConnectionTypeEventData$instance extends EventData {
    readonly __tsonic_type_Microsoft_EntityFrameworkCore_Sqlite_Diagnostics_Internal_UnexpectedConnectionTypeEventData: never;

    readonly ConnectionType: Type;
}


export const UnexpectedConnectionTypeEventData: {
    new(eventDefinition: EventDefinitionBase, messageGenerator: Func_3<EventDefinitionBase, EventData, System_Internal.String>, connectionType: Type): UnexpectedConnectionTypeEventData;
};


export type UnexpectedConnectionTypeEventData = UnexpectedConnectionTypeEventData$instance;

